# translate_vi_to_en.py
# Run: python tool/translate_vi_to_en.py
# Replaces Vietnamese UI strings with English across all .dart files in lib/

import os
import glob

root = os.path.join(os.path.dirname(__file__), '..', 'lib')

translations = [
    # ── longest first to avoid partial replacements ──
    ('Bắt đầu ca làm việc', 'Start Shift'),
    ('Kết thúc ca làm việc', 'End Shift'),
    ('Kết thúc ca', 'End Shift'),
    ('Xem chi tiết ca', 'View Shift Details'),
    ('Mở ca mới', 'Open New Shift'),
    ('Đóng ca', 'Close Shift'),
    ('Xác nhận đóng ca', 'Confirm Close Shift'),
    ('Thanh toán thành công', 'Payment Successful'),
    ('Thanh toán', 'Payment'),
    ('Gửi bếp', 'Send to Kitchen'),
    ('GỬI BẾP', 'SEND TO KITCHEN'),
    ('Gọi món', 'Order'),
    ('Thêm vào giỏ', 'Add to Cart'),
    ('Xóa giỏ hàng', 'Clear Cart'),
    ('Xóa hết', 'Clear All'),
    ('Xoá tất cả', 'Clear All'),
    ('Tạo đơn hàng mới', 'New Order'),
    ('Đặt hàng', 'Place Order'),
    ('Lưu thay đổi', 'Save Changes'),
    ('Lưu cài đặt', 'Save Settings'),
    ('Lưu', 'Save'),
    ('Huỷ', 'Cancel'),
    ('Hủy', 'Cancel'),
    ('Đóng', 'Close'),
    ('Thêm mới', 'Add New'),
    ('Thêm', 'Add'),
    ('Xoá', 'Delete'),
    ('Xóa', 'Delete'),
    ('Chỉnh sửa', 'Edit'),
    ('Sửa', 'Edit'),
    ('Cập nhật', 'Update'),
    ('Xác nhận', 'Confirm'),
    ('Thoát', 'Exit'),
    ('Đăng xuất', 'Logout'),
    ('Đăng nhập', 'Login'),
    ('Tìm kiếm...', 'Search...'),
    ('Tìm kiếm', 'Search'),
    ('Tìm...', 'Search...'),
    ('Đang tìm kiếm', 'Searching'),
    ('Kết quả tìm kiếm', 'Search Results'),
    ('Tải lại', 'Reload'),
    ('Làm mới', 'Refresh'),
    ('Áp dụng', 'Apply'),
    ('Tiếp tục', 'Continue'),
    ('Quay lại', 'Go Back'),
    ('Trở về', 'Back'),
    ('In hóa đơn', 'Print Receipt'),
    ('In', 'Print'),
    ('Xuất', 'Export'),
    ('Nhập', 'Import'),
    ('Tải xuống', 'Download'),
    ('Tải lên', 'Upload'),
    ('Chọn tất cả', 'Select All'),
    ('Bỏ chọn', 'Deselect'),
    ('Chọn', 'Select'),
    ('Bỏ qua', 'Skip'),
    ('Gọi nhân viên', 'Call Staff'),

    # Navigation / Tabs
    ('Trang chủ', 'Home'),
    ('Bán hàng', 'Sales'),
    ('Quản lý', 'Management'),
    ('Cài đặt', 'Settings'),
    ('Báo cáo', 'Reports'),
    ('Thực đơn', 'Menu'),
    ('Thống kê', 'Statistics'),
    ('Tổng quan', 'Overview'),
    ('Lịch sử đơn hàng', 'Order History'),
    ('Lịch sử', 'History'),
    ('Danh sách', 'List'),
    ('Chi tiết', 'Details'),
    ('Hồ sơ', 'Profile'),
    ('Tài khoản', 'Account'),
    ('Người dùng', 'Users'),
    ('Danh mục', 'Category'),
    ('Kho hàng', 'Warehouse'),
    ('Nhà cung cấp', 'Suppliers'),
    ('Hóa đơn', 'Invoices'),
    ('Chứng từ', 'Documents'),
    ('Khuyến mãi', 'Promotions'),
    ('Tích điểm', 'Loyalty Points'),
    ('Điểm thưởng', 'Reward Points'),
    ('Liên hệ', 'Contacts'),
    ('Chi phí', 'Expenses'),
    ('Mua hàng', 'Purchase'),
    ('Bán lẻ', 'Retail'),
    ('Máy in', 'Printers'),
    ('Khách hàng', 'Customers'),
    ('Nhân viên', 'Staff'),
    ('Sản phẩm', 'Products'),

    # POS specific
    ('Giỏ hàng trống', 'Cart is empty'),
    ('Giỏ hàng', 'Cart'),
    ('Tổng tiền', 'Total'),
    ('Tổng cộng', 'Grand Total'),
    ('Tổng', 'Total'),
    ('Giảm giá', 'Discount'),
    ('Thuế', 'Tax'),
    ('Tiền mặt', 'Cash'),
    ('Thẻ', 'Card'),
    ('Chuyển khoản', 'Bank Transfer'),
    ('Tiền thừa', 'Change'),
    ('Tiền khách đưa', 'Amount Received'),
    ('Phương thức thanh toán', 'Payment Method'),
    ('Số lượng', 'Quantity'),
    ('Đơn giá', 'Unit Price'),
    ('Thành tiền', 'Subtotal'),
    ('Ghi chú đơn hàng', 'Order Notes'),
    ('Ghi chú', 'Notes'),
    ('Chọn bàn trước', 'Please select a table first'),
    ('Vui lòng chọn bàn', 'Please select a table'),
    ('Chọn bàn', 'Select Table'),
    ('Bàn', 'Table'),
    ('Khu vực', 'Zone'),
    ('Loại đơn', 'Order Type'),
    ('Ăn tại bàn', 'Dine In'),
    ('Mang về', 'Take Away'),
    ('Giao hàng', 'Delivery'),
    ('Đơn hàng', 'Order'),
    ('Mã đơn', 'Order ID'),
    ('Trạng thái', 'Status'),
    ('Đang chờ', 'Pending'),
    ('Đang xử lý', 'Processing'),
    ('Đã xong', 'Completed'),
    ('Đã hủy', 'Cancelled'),
    ('Đã thanh toán', 'Paid'),
    ('Chưa thanh toán', 'Unpaid'),
    ('Thời gian', 'Time'),
    ('Hôm nay', 'Today'),
    ('Tuần này', 'This Week'),
    ('Tháng này', 'This Month'),
    ('Ngày', 'Date'),
    ('Tháng', 'Month'),
    ('Năm', 'Year'),

    # Menu management
    ('Tên món', 'Item Name'),
    ('Tên sản phẩm', 'Product Name'),
    ('Tên danh mục', 'Category Name'),
    ('Giá bán', 'Selling Price'),
    ('Giá gốc', 'Original Price'),
    ('Giá nhập', 'Purchase Price'),
    ('Giá vốn', 'Cost Price'),
    ('Mô tả', 'Description'),
    ('Hình ảnh', 'Image'),
    ('Biểu tượng', 'Emoji / Icon'),
    ('Còn hàng', 'In Stock'),
    ('Hết hàng', 'Out of Stock'),
    ('Tồn kho', 'Stock'),
    ('Nhóm món', 'Item Group'),
    ('Công thức', 'Recipe'),
    ('Tùy chọn', 'Options'),

    # Settings
    ('Ngôn ngữ', 'Language'),
    ('Tiếng Việt', 'Vietnamese'),
    ('Tiếng Anh', 'English'),
    ('Múi giờ', 'Timezone'),
    ('Tiền tệ', 'Currency'),
    ('Định dạng', 'Format'),
    ('Màu sắc', 'Color'),
    ('Giao diện', 'Interface'),
    ('Chế độ tối', 'Dark Mode'),
    ('Âm thanh', 'Sound'),
    ('Thông báo', 'Notifications'),
    ('Kết nối', 'Connection'),
    ('Địa chỉ máy chủ', 'Server Address'),
    ('Máy chủ', 'Server'),
    ('Mật khẩu mới', 'New Password'),
    ('Xác nhận mật khẩu', 'Confirm Password'),
    ('Mật khẩu', 'Password'),
    ('Tên người dùng', 'Username'),
    ('Email', 'Email'),
    ('Số điện thoại', 'Phone Number'),
    ('Địa chỉ IP', 'IP Address'),
    ('Địa chỉ', 'Address'),
    ('Chọn chi nhánh', 'Select Branch'),
    ('Chi nhánh', 'Branch'),
    ('Vai trò', 'Role'),
    ('Quyền hạn', 'Permissions'),
    ('Quản trị viên', 'Administrator'),
    ('Thu ngân', 'Cashier'),
    ('Tên nhà hàng', 'Restaurant Name'),
    ('Nhà hàng', 'Restaurant'),

    # Messages / toasts
    ('Thành công', 'Success'),
    ('Lỗi', 'Error'),
    ('Cảnh báo', 'Warning'),
    ('Thông tin', 'Info'),
    ('Đang tải', 'Loading'),
    ('Vui lòng đợi', 'Please wait'),
    ('Không có dữ liệu', 'No data'),
    ('Không tìm thấy', 'Not found'),
    ('Không có kết nối mạng', 'No network connection'),
    ('Đã lưu thành công', 'Saved successfully'),
    ('Lưu thất bại', 'Save failed'),
    ('Xóa thành công', 'Deleted successfully'),
    ('Xóa thất bại', 'Delete failed'),
    ('Kết nối thành công', 'Connected successfully'),
    ('Kết nối thất bại', 'Connection failed'),
    ('Vui lòng điền đầy đủ', 'Please fill in all fields'),
    ('Bắt buộc', 'Required'),
    ('Tuỳ chọn', 'Optional'),
    ('Đồng ý', 'Agree'),
    ('Từ chối', 'Reject'),
    ('Có', 'Yes'),
    ('Không', 'No'),

    # Reports
    ('Doanh thu', 'Revenue'),
    ('Lợi nhuận', 'Profit'),
    ('Số lần bán', 'Number of Sales'),
    ('Khách hàng mới', 'New Customers'),
    ('Sản phẩm bán chạy', 'Top Selling Items'),
    ('Ca làm việc', 'Shift'),
    ('Mở ca', 'Open Shift'),
    ('Tiền đầu ca', 'Opening Cash'),
    ('Tiền cuối ca', 'Closing Cash'),
    ('Tổng thu', 'Total Revenue'),
    ('Tổng chi', 'Total Expenses'),

    # Shift dialog
    ('Thông tin ca', 'Shift Info'),
    ('Nhân viên mở ca', 'Opened by'),
    ('Thời gian mở', 'Open Time'),
    ('Thời gian đóng', 'Close Time'),
    ('Tổng đơn hàng', 'Total Orders'),
    ('Doanh số', 'Sales'),

    # KDS
    ('Màn hình bếp', 'Kitchen Display'),
    ('Màn Bếp', 'KDS'),
    ('Đơn mới', 'New Order'),
    ('Đang làm', 'In Progress'),
    ('Hoàn thành', 'Done'),
    ('Tất cả', 'All'),
    ('Xong', 'Done'),

    # Printer
    ('Thêm máy in', 'Add Printer'),
    ('Kiểm tra in', 'Test Print'),
    ('Kết nối máy in', 'Connect Printer'),
    ('Loại máy in', 'Printer Type'),
    ('Tên máy in', 'Printer Name'),
    ('Khổ giấy', 'Paper Size'),

    # Loyalty
    ('Chương trình tích điểm', 'Loyalty Program'),
    ('Đổi điểm', 'Redeem Points'),
    ('Tỷ lệ tích điểm', 'Points Rate'),
    ('Hạng thành viên', 'Membership Tier'),
    ('Số điểm', 'Points'),

    # Misc
    ('Không có món nào', 'No items'),
    ('Tất cả danh mục', 'All Categories'),
    ('Nhập mã PIN', 'Enter PIN'),
    ('Sai mã PIN', 'Wrong PIN'),
    ('Mã PIN', 'PIN'),
    ('Phiên đăng nhập hết hạn', 'Login session expired'),
    ('Token hết hạn', 'Session expired'),
    ('Phiên làm việc', 'Session'),
    ('Đang kết nối', 'Connecting'),
    ('Mất kết nối', 'Disconnected'),
    ('Phiên bản', 'Version'),
    ('Cập nhật phần mềm', 'Software Update'),
    ('Điều khoản', 'Terms'),
    ('Chính sách', 'Policy'),
    ('Bảo mật', 'Security'),
    ('Sao lưu', 'Backup'),
    ('Khôi phục', 'Restore'),
    ('Đồng bộ', 'Sync'),
    ('Hệ thống', 'System'),
    ('Tên', 'Name'),
    ('Mạng', 'Network'),
    ('Chuẩn bị', 'Preparing'),
    ('Chờ xác nhận', 'Awaiting Confirmation'),
    ('Đang giao', 'Delivering'),
    ('Đã giao', 'Delivered'),
    ('Nhận hàng', 'Receive'),
    ('Trả hàng', 'Return'),
    ('Đặt lại', 'Reset'),
    ('Mặc định', 'Default'),
    ('Tùy chỉnh', 'Custom'),
    ('Nâng cao', 'Advanced'),
    ('Cơ bản', 'Basic'),
    ('Thêm tùy chọn', 'Add Option'),
    ('Xóa tùy chọn', 'Remove Option'),
    ('Nhập tên', 'Enter name'),
    ('Nhập giá', 'Enter price'),
    ('Nhập số lượng', 'Enter quantity'),
    ('Nhập ghi chú', 'Enter notes'),
    ('Đang tìm kiếm', 'Searching'),
    ('Xem tất cả', 'View All'),
    ('Xem thêm', 'View More'),
    ('Thu gọn', 'Collapse'),
    ('Mở rộng', 'Expand'),
    ('Sắp xếp', 'Sort'),
    ('Lọc', 'Filter'),
    ('Từ ngày', 'From Date'),
    ('Đến ngày', 'To Date'),
    ('Chọn ngày', 'Select Date'),
    ('Thứ Hai', 'Monday'),
    ('Thứ Ba', 'Tuesday'),
    ('Thứ Tư', 'Wednesday'),
    ('Thứ Năm', 'Thursday'),
    ('Thứ Sáu', 'Friday'),
    ('Thứ Bảy', 'Saturday'),
    ('Chủ Nhật', 'Sunday'),
    ('Đã thêm vào giỏ', 'Added to cart'),
    ('Đã xóa khỏi giỏ', 'Removed from cart'),
    ('Đơn hàng đã được gửi', 'Order sent'),
    ('Cảm ơn bạn!', 'Thank you!'),
    ('Đơn của bạn đã được gửi', 'Your order has been placed'),
    ('In thành công', 'Printed successfully'),
    ('In thất bại', 'Print failed'),
    ('Dữ liệu', 'Data'),
    ('Công ty', 'Company'),
    ('Mạng', 'Network'),
    ('Logo', 'Logo'),
]

dart_files = glob.glob(os.path.join(root, '**', '*.dart'), recursive=True)
updated = 0

for fpath in dart_files:
    with open(fpath, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
    original = content
    for vi, en in translations:
        content = content.replace(vi, en)
    if content != original:
        with open(fpath, 'w', encoding='utf-8') as f:
            f.write(content)
        updated += 1
        print(f'Translated: {os.path.basename(fpath)}')

print(f'\nDone. {updated} files updated.')
