# translate_vi_to_en.ps1
# Replaces Vietnamese UI strings with English across all .dart files in lib/
# Run from dandpak_pos root: pwsh tool/translate_vi_to_en.ps1

$root = Join-Path $PSScriptRoot ".." "lib"
$dartFiles = Get-ChildItem -Path $root -Recurse -Filter "*.dart"

# ── Translation table: ordered longest-first to avoid partial replacements ────
$translations = [ordered]@{
  # ── Buttons / actions ──────────────────────────────────────────────────────
  'Bắt đầu ca làm việc'         = 'Start Shift'
  'Kết thúc ca'                  = 'End Shift'
  'Kết thúc ca làm việc'        = 'End Shift'
  'Xem chi tiết ca'             = 'View Shift Details'
  'Mở ca mới'                   = 'Open New Shift'
  'Đóng ca'                     = 'Close Shift'
  'Xác nhận đóng ca'            = 'Confirm Close Shift'
  'Thanh toán'                  = 'Payment'
  'Thanh toán thành công'       = 'Payment Successful'
  'Đặt hàng'                    = 'Place Order'
  'Gửi bếp'                     = 'Send to Kitchen'
  'GỬI BẾP'                     = 'SEND TO KITCHEN'
  'Gọi món'                     = 'Order'
  'Thêm vào giỏ'               = 'Add to Cart'
  'Xóa giỏ hàng'               = 'Clear Cart'
  'Xóa hết'                     = 'Clear All'
  'Xoá tất cả'                  = 'Clear All'
  'Tạo đơn hàng mới'           = 'New Order'
  'Đơn hàng mới'               = 'New Order'
  'Lưu thay đổi'               = 'Save Changes'
  'Lưu cài đặt'                 = 'Save Settings'
  'Lưu'                         = 'Save'
  'Hủy'                         = 'Cancel'
  'Huỷ'                         = 'Cancel'
  'Đóng'                        = 'Close'
  'Thêm mới'                    = 'Add New'
  'Thêm'                        = 'Add'
  'Xóa'                         = 'Delete'
  'Xoá'                         = 'Delete'
  'Sửa'                         = 'Edit'
  'Chỉnh sửa'                   = 'Edit'
  'Cập nhật'                    = 'Update'
  'Xác nhận'                    = 'Confirm'
  'Thoát'                       = 'Exit'
  'Đăng xuất'                   = 'Logout'
  'Đăng nhập'                   = 'Login'
  'Tìm kiếm'                    = 'Search'
  'Tải lại'                     = 'Reload'
  'Làm mới'                     = 'Refresh'
  'Áp dụng'                     = 'Apply'
  'Tiếp tục'                    = 'Continue'
  'Quay lại'                    = 'Go Back'
  'Trở về'                      = 'Back'
  'In hóa đơn'                  = 'Print Receipt'
  'In'                          = 'Print'
  'Xuất'                        = 'Export'
  'Nhập'                        = 'Import'
  'Tải xuống'                   = 'Download'
  'Tải lên'                     = 'Upload'
  'Chọn'                        = 'Select'
  'Chọn tất cả'                 = 'Select All'
  'Bỏ chọn'                     = 'Deselect'
  'Bỏ qua'                      = 'Skip'
  'Gọi nhân viên'               = 'Call Staff'

  # ── Navigation / Tabs ──────────────────────────────────────────────────────
  'Trang chủ'                   = 'Home'
  'Bán hàng'                    = 'Sales'
  'Quản lý'                     = 'Management'
  'Cài đặt'                     = 'Settings'
  'Báo cáo'                     = 'Reports'
  'Thực đơn'                    = 'Menu'
  'Thống kê'                    = 'Statistics'
  'Tổng quan'                   = 'Overview'
  'Dashboard'                   = 'Dashboard'
  'Lịch sử đơn hàng'           = 'Order History'
  'Lịch sử'                     = 'History'
  'Danh sách'                   = 'List'
  'Chi tiết'                    = 'Details'
  'Hồ sơ'                       = 'Profile'
  'Tài khoản'                   = 'Account'
  'Người dùng'                  = 'Users'
  'Nhân viên'                   = 'Staff'
  'Khách hàng'                  = 'Customers'
  'Sản phẩm'                    = 'Products'
  'Danh mục'                    = 'Category'
  'Kho hàng'                    = 'Warehouse'
  'Nhà cung cấp'               = 'Suppliers'
  'Hóa đơn'                     = 'Invoices'
  'Chứng từ'                    = 'Documents'
  'Khuyến mãi'                  = 'Promotions'
  'Tích điểm'                   = 'Loyalty Points'
  'Điểm thưởng'                 = 'Reward Points'
  'Liên hệ'                     = 'Contacts'
  'Chi phí'                     = 'Expenses'
  'Mua hàng'                    = 'Purchase'
  'Bán lẻ'                      = 'Retail'
  'Online'                      = 'Online'
  'Kiosk'                       = 'Kiosk'
  'Máy in'                      = 'Printers'

  # ── POS specific ───────────────────────────────────────────────────────────
  'Giỏ hàng'                    = 'Cart'
  'Tổng tiền'                   = 'Total'
  'Tổng cộng'                   = 'Grand Total'
  'Tổng'                        = 'Total'
  'Giảm giá'                    = 'Discount'
  'Thuế'                        = 'Tax'
  'Tiền mặt'                    = 'Cash'
  'Thẻ'                         = 'Card'
  'Chuyển khoản'                = 'Bank Transfer'
  'Tiền thừa'                   = 'Change'
  'Tiền khách đưa'             = 'Amount Received'
  'Phương thức thanh toán'     = 'Payment Method'
  'Số lượng'                    = 'Quantity'
  'Đơn giá'                     = 'Unit Price'
  'Thành tiền'                  = 'Subtotal'
  'Ghi chú'                     = 'Notes'
  'Ghi chú đơn hàng'           = 'Order Notes'
  'Bàn'                         = 'Table'
  'Chọn bàn'                    = 'Select Table'
  'Khu vực'                     = 'Zone'
  'Loại đơn'                    = 'Order Type'
  'Ăn tại bàn'                  = 'Dine In'
  'Mang về'                     = 'Take Away'
  'Giao hàng'                   = 'Delivery'
  'Đơn hàng'                    = 'Order'
  'Mã đơn'                      = 'Order ID'
  'Trạng thái'                  = 'Status'
  'Đang chờ'                    = 'Pending'
  'Đang xử lý'                  = 'Processing'
  'Đã xong'                     = 'Completed'
  'Đã hủy'                      = 'Cancelled'
  'Đã thanh toán'               = 'Paid'
  'Chưa thanh toán'             = 'Unpaid'
  'Thời gian'                   = 'Time'
  'Ngày'                        = 'Date'
  'Tháng'                       = 'Month'
  'Năm'                         = 'Year'
  'Hôm nay'                     = 'Today'
  'Tuần này'                    = 'This Week'
  'Tháng này'                   = 'This Month'

  # ── Menu management ────────────────────────────────────────────────────────
  'Tên món'                     = 'Item Name'
  'Tên sản phẩm'                = 'Product Name'
  'Tên danh mục'                = 'Category Name'
  'Giá bán'                     = 'Selling Price'
  'Giá gốc'                     = 'Original Price'
  'Giá nhập'                    = 'Purchase Price'
  'Giá vốn'                     = 'Cost Price'
  'Mô tả'                       = 'Description'
  'Hình ảnh'                    = 'Image'
  'Ảnh'                         = 'Photo'
  'Biểu tượng'                  = 'Emoji / Icon'
  'Còn hàng'                    = 'In Stock'
  'Hết hàng'                    = 'Out of Stock'
  'Tồn kho'                     = 'Stock'
  'Nhóm món'                    = 'Item Group'
  'Công thức'                   = 'Recipe'
  'Tùy chọn'                    = 'Options'
  'Topping'                     = 'Toppings'

  # ── Settings ───────────────────────────────────────────────────────────────
  'Ngôn ngữ'                    = 'Language'
  'Tiếng Việt'                  = 'Vietnamese'
  'Tiếng Anh'                   = 'English'
  'Múi giờ'                     = 'Timezone'
  'Tiền tệ'                     = 'Currency'
  'Định dạng'                   = 'Format'
  'Màu sắc'                     = 'Color'
  'Giao diện'                   = 'Interface'
  'Chế độ tối'                  = 'Dark Mode'
  'Âm thanh'                    = 'Sound'
  'Thông báo'                   = 'Notifications'
  'Kết nối'                     = 'Connection'
  'Máy chủ'                     = 'Server'
  'Địa chỉ máy chủ'            = 'Server Address'
  'Cổng'                        = 'Port'
  'Mật khẩu'                    = 'Password'
  'Mật khẩu mới'               = 'New Password'
  'Xác nhận mật khẩu'         = 'Confirm Password'
  'Tên người dùng'             = 'Username'
  'Tên'                         = 'Name'
  'Email'                       = 'Email'
  'Số điện thoại'               = 'Phone Number'
  'Địa chỉ'                     = 'Address'
  'Chi nhánh'                   = 'Branch'
  'Chọn chi nhánh'             = 'Select Branch'
  'Vai trò'                     = 'Role'
  'Quyền hạn'                   = 'Permissions'
  'Quản trị viên'               = 'Administrator'
  'Thu ngân'                    = 'Cashier'
  'Nhà hàng'                    = 'Restaurant'
  'Tên nhà hàng'               = 'Restaurant Name'
  'Logo'                        = 'Logo'

  # ── Messages ───────────────────────────────────────────────────────────────
  'Thành công'                  = 'Success'
  'Lỗi'                         = 'Error'
  'Cảnh báo'                   = 'Warning'
  'Thông tin'                   = 'Info'
  'Đang tải'                    = 'Loading'
  'Vui lòng đợi'               = 'Please wait'
  'Không có dữ liệu'           = 'No data'
  'Không tìm thấy'             = 'Not found'
  'Đã lưu thành công'         = 'Saved successfully'
  'Lưu thất bại'               = 'Save failed'
  'Xóa thành công'             = 'Deleted successfully'
  'Xóa thất bại'               = 'Delete failed'
  'Kết nối thành công'        = 'Connected successfully'
  'Kết nối thất bại'          = 'Connection failed'
  'Vui lòng điền đầy đủ'     = 'Please fill in all fields'
  'Bắt buộc'                   = 'Required'
  'Tuỳ chọn'                   = 'Optional'
  'Có'                          = 'Yes'
  'Không'                       = 'No'
  'OK'                          = 'OK'
  'Đồng ý'                     = 'Agree'
  'Từ chối'                    = 'Reject'

  # ── Reports ────────────────────────────────────────────────────────────────
  'Doanh thu'                   = 'Revenue'
  'Lợi nhuận'                   = 'Profit'
  'Chi phí'                     = 'Expenses'
  'Số lần bán'                  = 'Number of Sales'
  'Khách hàng mới'             = 'New Customers'
  'Đơn hàng mới'               = 'New Orders'
  'Sản phẩm bán chạy'         = 'Top Selling Items'
  'Nhân viên'                   = 'Staff'
  'Ca làm việc'                 = 'Shift'
  'Mở ca'                       = 'Open Shift'
  'Đóng ca'                     = 'Close Shift'
  'Tiền đầu ca'                 = 'Opening Cash'
  'Tiền cuối ca'               = 'Closing Cash'
  'Tổng thu'                    = 'Total Revenue'
  'Tổng chi'                    = 'Total Expenses'

  # ── Shift dialog ───────────────────────────────────────────────────────────
  'Thông tin ca'               = 'Shift Info'
  'Nhân viên mở ca'           = 'Opened by'
  'Thời gian mở'              = 'Open Time'
  'Thời gian đóng'            = 'Close Time'
  'Tổng đơn hàng'             = 'Total Orders'
  'Doanh số'                   = 'Sales'

  # ── KDS ────────────────────────────────────────────────────────────────────
  'Màn hình bếp'               = 'Kitchen Display'
  'Màn Bếp'                    = 'KDS'
  'Đơn mới'                    = 'New Order'
  'Đang làm'                   = 'In Progress'
  'Hoàn thành'                 = 'Done'
  'Tất cả'                     = 'All'
  'Xong'                       = 'Done'

  # ── Printer ────────────────────────────────────────────────────────────────
  'Thêm máy in'                = 'Add Printer'
  'Kiểm tra in'               = 'Test Print'
  'Kết nối máy in'            = 'Connect Printer'
  'Loại máy in'               = 'Printer Type'
  'Tên máy in'                = 'Printer Name'
  'Khổ giấy'                  = 'Paper Size'

  # ── Loyalty ────────────────────────────────────────────────────────────────
  'Chương trình tích điểm'   = 'Loyalty Program'
  'Đổi điểm'                  = 'Redeem Points'
  'Số điểm'                   = 'Points'
  'Tỷ lệ tích điểm'          = 'Points Rate'
  'Hạng thành viên'          = 'Membership Tier'

  # ── Misc labels ────────────────────────────────────────────────────────────
  'Tất cả danh mục'           = 'All Categories'
  'Không có món nào'          = 'No items'
  'Giỏ hàng trống'            = 'Cart is empty'
  'Chọn bàn trước'           = 'Please select a table first'
  'Vui lòng chọn bàn'        = 'Please select a table'
  'Mã PIN'                    = 'PIN'
  'Nhập mã PIN'               = 'Enter PIN'
  'Sai mã PIN'                = 'Wrong PIN'
  'Phiên làm việc'            = 'Session'
  'Đang kết nối'              = 'Connecting'
  'Mất kết nối'               = 'Disconnected'
  'Phiên bản'                 = 'Version'
  'Cập nhật phần mềm'        = 'Software Update'
  'Điều khoản'                = 'Terms'
  'Chính sách'                = 'Policy'
  'Bảo mật'                   = 'Security'
  'Sao lưu'                   = 'Backup'
  'Khôi phục'                 = 'Restore'
  'Dữ liệu'                   = 'Data'
  'Đồng bộ'                   = 'Sync'
  'Hệ thống'                  = 'System'
  'Công ty'                   = 'Company'
  'Địa chỉ IP'               = 'IP Address'
  'Mạng'                      = 'Network'
  'Wifi'                      = 'WiFi'
  'Bluetooth'                 = 'Bluetooth'
  'USB'                       = 'USB'
  'Chuẩn bị'                  = 'Preparing'
  'Chờ xác nhận'             = 'Awaiting Confirmation'
  'Đang giao'                 = 'Delivering'
  'Đã giao'                   = 'Delivered'
  'Nhận hàng'                 = 'Receive'
  'Trả hàng'                  = 'Return'
  'Đặt lại'                   = 'Reset'
  'Mặc định'                  = 'Default'
  'Tùy chỉnh'                 = 'Custom'
  'Nâng cao'                  = 'Advanced'
  'Cơ bản'                    = 'Basic'
  'Thêm tùy chọn'            = 'Add Option'
  'Xóa tùy chọn'             = 'Remove Option'
  'Nhập tên'                  = 'Enter name'
  'Nhập giá'                  = 'Enter price'
  'Nhập số lượng'            = 'Enter quantity'
  'Nhập ghi chú'             = 'Enter notes'
  'Tìm kiếm...'               = 'Search...'
  'Tìm...'                    = 'Search...'
  'Đang tìm kiếm'            = 'Searching'
  'Kết quả tìm kiếm'        = 'Search Results'
  'Xem tất cả'               = 'View All'
  'Xem thêm'                  = 'View More'
  'Thu gọn'                   = 'Collapse'
  'Mở rộng'                   = 'Expand'
  'Sắp xếp'                   = 'Sort'
  'Lọc'                       = 'Filter'
  'Từ ngày'                   = 'From Date'
  'Đến ngày'                  = 'To Date'
  'Chọn ngày'                 = 'Select Date'
  'Thứ Hai'                   = 'Monday'
  'Thứ Ba'                    = 'Tuesday'
  'Thứ Tư'                    = 'Wednesday'
  'Thứ Năm'                   = 'Thursday'
  'Thứ Sáu'                   = 'Friday'
  'Thứ Bảy'                   = 'Saturday'
  'Chủ Nhật'                  = 'Sunday'

  # ── Snackbars / Toasts ─────────────────────────────────────────────────────
  'Đã thêm vào giỏ'           = 'Added to cart'
  'Đã xóa khỏi giỏ'          = 'Removed from cart'
  'Đơn hàng đã được gửi'     = 'Order sent'
  'Cảm ơn bạn!'              = 'Thank you!'
  'Đơn của bạn đã được gửi'  = 'Your order has been placed'
  'In thành công'             = 'Printed successfully'
  'In thất bại'               = 'Print failed'
  'Không có kết nối mạng'    = 'No network connection'
  'Token hết hạn'             = 'Session expired'
  'Phiên đăng nhập hết hạn'  = 'Login session expired'
}

$count = 0
foreach ($file in $dartFiles) {
  $content = Get-Content $file.FullName -Raw -Encoding UTF8
  $original = $content
  foreach ($vi in $translations.Keys) {
    $en = $translations[$vi]
    $content = $content.Replace($vi, $en)
  }
  if ($content -ne $original) {
    Set-Content -Path $file.FullName -Value $content -Encoding UTF8 -NoNewline
    $count++
    Write-Host "Translated: $($file.Name)"
  }
}
Write-Host "`nDone. $count files updated."
