name: dandpak_kds
description: "Dan D Pak KDS — Flutter prototype (native, nhẹ cho máy POS yếu)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
