// Inventory Core: two warehouse domains (kitchen + retail), lot/expiry
// tracking, FEFO issues, stocktake sessions, and legacy summary stock support.
import { readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { db, uid, now, audit, defaultWarehouseId } from '../db.js';
import { emit } from '../realtime.js';
import { matchesSearch, searchTokens } from '../core/search.js';
import { getRetailConfig } from './settings.js';
import { salePrice } from './tax.js';

// Ảnh sản phẩm import từ KiotViet nằm ở server/assets/product-images dưới tên
// kv_{barcode}.* (trước ở web/assets — web/ đã gỡ khỏi repo; đường dẫn này
// khớp route static /assets của index.js). Nhiều SKU chưa gán trường image
// trong DB → tự khớp theo barcode (quét thư mục 1 lần, cache RAM) để POS hiển
// thị ảnh thật thay vì ô trống.
const PRODUCT_IMG_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'product-images');
let _productImgIndex = null;
function productImageForBarcode(barcode) {
  const bc = String(barcode || '').trim();
  if (!bc) return null;
  if (!_productImgIndex) {
    _productImgIndex = new Map();
    try {
      for (const f of readdirSync(PRODUCT_IMG_DIR)) {
        const m = /^kv_(.+)\.(jpg|jpeg|png|webp)$/i.exec(f);
        if (m && !_productImgIndex.has(m[1])) {
          _productImgIndex.set(m[1], `/assets/product-images/${f}`);
        }
      }
    } catch { /* thư mục có thể không tồn tại khi deploy tách asset */ }
  }
  return _productImgIndex.get(bc) || null;
}

function withProductImage(row) {
  if (row && !row.image) {
    const img = productImageForBarcode(row.barcode);
    if (img) row.image = img;
  }
  return row;
}

const DEFAULT_WAREHOUSE = { inventory: 'wh_kitchen', sku: 'wh_retail' };
const fallbackWarehouse = (branch_id, stockType) => defaultWarehouseId(branch_id, stockType) || DEFAULT_WAREHOUSE[stockType];
const SALES_CHANNELS = new Set(['ipad', 'pos', 'retail', 'online', 'grabmerchant', 'shopeefood', 'befood', 'grabmart', 'website']);
// Document types generated by SELLING (order fulfilment), not by warehouse ops.
// These never belong in the "Phiếu nhập/xuất" tab — the sales record is the bill
// in the invoices/payments module. Filtered out of listDocuments; new sales no
// longer create documents at all (see issueGeneric/deductForOrder skipDocument).
const SALE_DOC_TYPES = new Set(['sale', 'recipe', 'retail_sale', 'return', 'retail_return']);

const asBool = (v) => v ? 1 : 0;
const textOr = (v, fallback) => (v !== undefined && v !== null && String(v).trim() !== '') ? String(v).trim() : fallback;
const nullableText = (v, fallback) => (v !== undefined) ? (String(v || '').trim() || null) : fallback;
const numberOr = (v, fallback) => {
  if (v === undefined || v === null || v === '') return fallback;
  const n = parseFloat(v);
  return Number.isFinite(n) ? n : fallback;
};
const intOr = (v, fallback) => {
  if (v === undefined || v === null || v === '') return fallback;
  const n = parseInt(v);
  return Number.isFinite(n) ? n : fallback;
};
const boolOr = (v, fallback) => (v === undefined || v === null) ? (fallback ? 1 : 0) : (v ? 1 : 0);
const qtyNum = (v, label = 'Số lượng') => {
  const n = parseFloat(v);
  if (!Number.isFinite(n) || n <= 0) throw new Error(label + ' không hợp lệ');
  return n;
};

// ---- Units of measure (alt units convert to the base `unit`) ----
function parseUnits(item) { try { return JSON.parse(item?.units_json || '[]'); } catch { return []; } }
function normalizeUnits(units) {
  if (!Array.isArray(units)) return [];
  return units.map(u => ({ name: String(u.name || '').trim(), factor: Number(u.factor) || 0 }))
    .filter(u => u.name && u.factor > 0);
}
function parseSalesChannels(row) {
  try {
    const parsed = JSON.parse(row?.sales_channels_json || '[]');
    return Array.isArray(parsed) ? parsed.filter(c => SALES_CHANNELS.has(c)) : [];
  } catch {
    return [];
  }
}
function normalizeSalesChannels(channels, type = 'retail') {
  if (!Array.isArray(channels)) return type === 'kitchen' ? ['ipad', 'pos'] : ['retail'];
  return [...new Set(channels.map(c => String(c || '').trim()).filter(c => SALES_CHANNELS.has(c)))];
}
function withWarehouseMeta(row) {
  return {
    ...row,
    active: !!row.active,
    sales_channels: parseSalesChannels(row),
  };
}
function warehouseIdsForChannel(branch_id, channel, type = null) {
  const key = String(channel || '').trim();
  if (!SALES_CHANNELS.has(key)) return null;
  return listWarehouses(branch_id)
    .filter(w => (!type || w.type === type) && parseSalesChannels(w).includes(key))
    .map(w => w.id);
}
// Which warehouses a sales channel should draw retail SKUs from. A valid channel
// that isn't linked to any ACTIVE warehouse yet (unconfigured) resolves to null =
// "no restriction", so the catalog is never blank just because of missing setup.
function channelWarehouseFilter(branch_id, channel) {
  if (!channel) return null;
  const ids = warehouseIdsForChannel(branch_id, channel, 'retail');
  if (ids === null) return null;      // unknown channel key → no filter
  return ids.length ? ids : null;     // known but unlinked → show all, don't blank
}

// ── Cấu hình bán retail (Cài đặt → Kho & kênh bán → retail_config) ─────────
// channel 'retail' = POS bán lẻ; 'fnb_retail' = mục "Thêm retail" trong POS
// F&B. Mỗi bên có thể ép KHO cụ thể + BẢNG GIÁ riêng; chưa cấu hình thì giữ
// hành vi cũ (kho theo liên kết kênh bán, giá = skus.price).
function retailSectionFor(branch_id, channel) {
  if (channel !== 'retail' && channel !== 'fnb_retail') return null;
  const cfg = getRetailConfig(branch_id);
  return channel === 'fnb_retail' ? cfg.fnb : cfg.standalone;
}

// Bảng giá đang áp cho kênh — null = dùng giá chung (default/tắt/không có).
function channelPriceBookId(branch_id, channel) {
  const sec = retailSectionFor(branch_id, channel);
  const id = sec?.price_book_id || 'default';
  if (id === 'default') return null;
  const b = db.prepare(`SELECT id,status FROM price_books WHERE id=? AND branch_id=?`).get(id, branch_id);
  return b && b.status !== 'inactive' ? b.id : null;
}

/// Áp giá bảng giá của kênh lên 1 row SKU (đã enrich). SKU không có giá riêng
/// trong bảng → giữ nguyên giá chung. price trả về là giá khách thanh toán.
export function applyChannelPrice(sku, branch_id, channel) {
  if (!sku) return sku;
  const bookId = channelPriceBookId(branch_id, channel);
  const row = bookId ? db.prepare(`SELECT price FROM price_book_items WHERE book_id=? AND sku_id=?`).get(bookId, sku.id) : null;
  const configuredPrice = Math.max(0, Math.round(Number(row?.price ?? sku.price) || 0));
  const vat = sku.vat == null ? null : Number(sku.vat);
  const includesVat = sku.price_includes_vat !== 0;
  const price_pre_tax = includesVat && vat > 0 ? Math.round(configuredPrice / (1 + vat / 100)) : configuredPrice;
  return { ...sku, configured_price: configuredPrice, price: salePrice(configuredPrice, vat, includesVat), price_pre_tax, price_book_id: row ? bookId : null };
}
// How many base units in 1 of `uom` (the entered unit name).
function unitFactor(item, uom) {
  if (!uom || uom === item.unit) return 1;
  const u = parseUnits(item).find(x => x.name === uom);
  return u ? (Number(u.factor) || 1) : 1;
}

export function listWarehouses(branch_id = 'br1', filters = {}) {
  const includeInactive = filters.all === '1' || filters.all === 1 || filters.include_inactive === '1' || filters.include_inactive === 1;
  const rows = db.prepare(`SELECT * FROM warehouses WHERE branch_id=? ORDER BY sort,name`).all(branch_id);
  const mapped = rows.map(withWarehouseMeta);
  return includeInactive ? mapped : mapped.filter(w => w.active);
}

export function createWarehouse(body, branch_id = 'br1') {
  const name = textOr(body.name, '');
  if (!name) throw new Error('Thiếu tên kho');
  const type = body.type === 'kitchen' ? 'kitchen' : 'retail';
  const salesChannels = normalizeSalesChannels(body.sales_channels || body.salesChannels, type);
  const code = normalizeWarehouseCode(body.code || name);
  const branchPrefix = branch_id === 'br1' ? '' : `${String(branch_id).replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase()}_`;
  const id = body.id || `${branchPrefix}wh_${code.toLowerCase()}`;
  const active = body.active !== undefined ? (body.active ? 1 : 0) : 1;
  const sort = intOr(body.sort, db.prepare(`SELECT COALESCE(MAX(sort),0)+1 n FROM warehouses WHERE branch_id=?`).get(branch_id).n);
  const dup = db.prepare(`SELECT id FROM warehouses WHERE id=? OR (branch_id=? AND code=?)`).get(id, branch_id, code);
  if (dup) throw new Error('Mã kho đã tồn tại');
  db.prepare(`INSERT INTO warehouses (id,branch_id,code,name,type,active,sort,sales_channels_json) VALUES (?,?,?,?,?,?,?,?)`)
    .run(id, branch_id, code, name, type, active, sort, JSON.stringify(salesChannels));
  audit('warehouse.create', { id, code, name, type, active, sales_channels: salesChannels }, branch_id);
  emit('inventory:updated', { warehouse: id }, branch_id);
  return withWarehouseMeta(db.prepare(`SELECT * FROM warehouses WHERE id=?`).get(id));
}

export function updateWarehouse(id, body, branch_id = 'br1') {
  const cur = db.prepare(`SELECT * FROM warehouses WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!cur) throw new Error('Kho không tồn tại');
  const code = body.code !== undefined ? normalizeWarehouseCode(body.code || cur.code) : cur.code;
  const name = textOr(body.name, cur.name);
  const type = body.type !== undefined ? (body.type === 'kitchen' ? 'kitchen' : 'retail') : cur.type;
  const active = body.active !== undefined ? (body.active ? 1 : 0) : cur.active;
  const sort = intOr(body.sort, cur.sort || 0);
  const salesChannels = body.sales_channels !== undefined || body.salesChannels !== undefined
    ? normalizeSalesChannels(body.sales_channels || body.salesChannels || [], type)
    : parseSalesChannels(cur);
  const dup = db.prepare(`SELECT id FROM warehouses WHERE branch_id=? AND code=? AND id!=?`).get(branch_id, code, id);
  if (dup) throw new Error('Mã kho đã tồn tại');
  // Never let a stock domain end up with zero active warehouses to sell from:
  // block turning off (or moving the type of) the last active warehouse of a type.
  if (cur.active && (active === 0 || type !== cur.type)) {
    const othersOfCurType = db.prepare(`SELECT COUNT(*) n FROM warehouses WHERE branch_id=? AND type=? AND active=1 AND id!=?`)
      .get(branch_id, cur.type, id).n;
    if (othersOfCurType === 0) {
      throw new Error(`Không thể tắt/đổi loại kho này — mỗi loại kho cần ít nhất một kho đang bật để phục vụ bán hàng (${cur.type === 'kitchen' ? 'kho bếp' : 'kho bán lẻ'}).`);
    }
  }
  db.prepare(`UPDATE warehouses SET code=?, name=?, type=?, active=?, sort=?, sales_channels_json=? WHERE id=? AND branch_id=?`)
    .run(code, name, type, active, sort, JSON.stringify(salesChannels), id, branch_id);
  audit('warehouse.update', { id, code, name, type, active, sales_channels: salesChannels }, branch_id);
  emit('inventory:updated', { warehouse: id }, branch_id);
  return withWarehouseMeta(db.prepare(`SELECT * FROM warehouses WHERE id=?`).get(id));
}

export function listInventory(branch_id = 'br1', filters = {}) {
  const rows = db.prepare(`SELECT * FROM inventory_items WHERE branch_id=? AND active=1 ORDER BY item_type,name`).all(branch_id);
  return rows
    .filter(i => !filters.item_type || i.item_type === filters.item_type)
    .filter(i => !filters.warehouse_id || (i.warehouse_id || fallbackWarehouse(branch_id, 'inventory')) === filters.warehouse_id)
    .map(i => enrichStockRow('inventory', i, filters.warehouse_id));
}

export function listSkus(branch_id = 'br1', filters = {}) {
  // Kho ép theo retail_config (nếu cấu hình); fnb_retail chưa cấu hình thì
  // rơi về mapping kênh 'retail' như trước — hành vi cũ không đổi.
  const sec = retailSectionFor(branch_id, filters.channel);
  const forcedWh = !filters.warehouse_id && sec?.warehouse_id ? sec.warehouse_id : '';
  const mapChannel = filters.channel === 'fnb_retail' ? 'retail' : filters.channel;
  const channelWarehouseIds =
      forcedWh ? null : channelWarehouseFilter(branch_id, mapChannel);
  const fallbackWh = fallbackWarehouse(branch_id, 'sku');

  let sql = `SELECT * FROM skus WHERE branch_id=? AND active=1`;
  const params = [branch_id];

  const search = searchTokens(filters.q || filters.search || filters.query);

  if (filters.warehouse_id || forcedWh) {
    sql += ` AND COALESCE(warehouse_id, ?) = ?`;
    params.push(fallbackWh, filters.warehouse_id || forcedWh);
  }

  if (channelWarehouseIds && channelWarehouseIds.length > 0) {
    sql += ` AND COALESCE(warehouse_id, ?) IN (${channelWarehouseIds.map(() => '?').join(',')})`;
    params.push(fallbackWh, ...channelWarehouseIds);
  }

  sql += ` ORDER BY name`;

  // ponytail: in-memory fold handles Vietnamese and cross-field tokens; add a
  // normalized indexed column if a measured catalog above 100k rows needs it.
  const matchedRows = db.prepare(sql).all(...params)
    .filter(s => matchesSearch([s.code, s.name, s.barcode, s.category, s.brand, s.unit], search));

  const page = intOr(filters.page, null);
  const limit = intOr(filters.limit, 40);

  if (page !== null && page > 0) {
    const offset = (page - 1) * limit;
    const total = matchedRows.length;
    const rows = matchedRows.slice(offset, offset + limit);
    const items = rows.map(s => withProductImage(applyChannelPrice(
        enrichStockRow('sku', s, filters.warehouse_id || forcedWh),
        branch_id, filters.channel)));
    return {
      items,
      total,
      page,
      limit,
    };
  }

  return matchedRows.map(s => withProductImage(applyChannelPrice(
      enrichStockRow('sku', s, filters.warehouse_id || forcedWh),
      branch_id, filters.channel)));
}

// Thiết lập giá (KiotViet PriceBook): mọi SKU đang bán kèm giá vốn, GIÁ NHẬP
// CUỐI (movement nhập gần nhất có giá > 0) và giá bán trước/sau thuế — client
// lọc theo điều kiện (nhỏ hơn/bằng/lớn hơn giá so sánh) và sửa giá từng dòng.
export function priceBook(branch_id = 'br1', filters = {}) {
  // book_id (≠ default): thêm cột book_price từ price_book_items — SKU chưa
  // đặt giá riêng trong bảng giá đó thì book_price = NULL (dùng giá chung).
  const bookId = String(filters.book_id || '').trim();
  const useBook = bookId && bookId !== 'default';
  const params = [];
  let sql = `
    SELECT s.id, s.code, s.barcode, s.name, s.emoji, s.image, s.unit, s.category, s.group_path,
      s.brand, s.stock, s.min_stock, s.cost, s.price, s.price_pre_tax, s.vat, s.price_includes_vat, s.warehouse_id,
      ${useBook ? 'pbi.price AS book_price,' : 'NULL AS book_price,'}
      (SELECT m.unit_cost FROM stock_movements m
        WHERE m.inventory_item_id=s.id AND m.item_type='sku'
          AND m.type IN ('receipt','opening') AND m.unit_cost>0
        ORDER BY m.created_at DESC LIMIT 1) AS last_in_cost
    FROM skus s`;
  if (useBook) {
    sql += ` LEFT JOIN price_book_items pbi ON pbi.book_id=? AND pbi.sku_id=s.id`;
    params.push(bookId);
  }
  sql += ` WHERE s.branch_id=? AND s.active=1`;
  params.push(branch_id);
  if (filters.warehouse_id) {
    sql += ` AND COALESCE(s.warehouse_id, ?) = ?`;
    params.push(fallbackWarehouse(branch_id, 'sku'), String(filters.warehouse_id));
  }
  sql += ` ORDER BY s.name`;
  return db.prepare(sql).all(...params).map(r => withProductImage({
    ...r,
    sale_price: salePrice(r.price, r.vat, r.price_includes_vat !== 0),
    low: (r.stock || 0) <= (r.min_stock || 0),
  }));
}

// ── Bảng giá (price books) — quản lý trong Cài đặt → Kho & kênh bán ─────────

/// Danh sách bảng giá; 'default' (Bảng giá chung = skus.price) luôn đứng đầu.
export function listPriceBooks(branch_id = 'br1') {
  const rows = db.prepare(
    `SELECT pb.*, (SELECT COUNT(*) FROM price_book_items i WHERE i.book_id=pb.id) AS item_count
     FROM price_books pb WHERE pb.branch_id=? ORDER BY pb.created_at`).all(branch_id);
  return [
    { id: 'default', name: 'Bảng giá chung', status: 'active', builtin: true, item_count: 0 },
    ...rows,
  ];
}

/// Tạo/sửa bảng giá: {id?, name, status}. Không đụng được bảng giá chung.
export function savePriceBookMeta(body = {}, branch_id = 'br1', user = {}) {
  const name = String(body.name || '').trim().slice(0, 120);
  const status = body.status === 'inactive' ? 'inactive' : 'active';
  const id = String(body.id || '').trim();
  if (id === 'default') throw new Error('Bảng giá chung là mặc định — không sửa được');
  if (!id && !name) throw new Error('Thiếu tên bảng giá');
  if (id) {
    const ex = db.prepare(`SELECT * FROM price_books WHERE id=? AND branch_id=?`).get(id, branch_id);
    if (!ex) throw new Error('Không tìm thấy bảng giá');
    db.prepare(`UPDATE price_books SET name=?, status=?, updated_at=? WHERE id=?`)
      .run(name || ex.name, status, now(), id);
    audit('pricebook.update', { id, name: name || ex.name, status }, branch_id, user?.username || user?.name);
    return db.prepare(`SELECT * FROM price_books WHERE id=?`).get(id);
  }
  const newId = uid('pb_');
  db.prepare(`INSERT INTO price_books (id,branch_id,name,status,created_at) VALUES (?,?,?,?,?)`)
    .run(newId, branch_id, name, status, now());
  audit('pricebook.create', { id: newId, name }, branch_id, user?.username || user?.name);
  return db.prepare(`SELECT * FROM price_books WHERE id=?`).get(newId);
}

export function deletePriceBookMeta(id, branch_id = 'br1', user = {}) {
  if (!id || id === 'default') throw new Error('Không xóa được bảng giá chung');
  const ex = db.prepare(`SELECT * FROM price_books WHERE id=? AND branch_id=?`).get(String(id), branch_id);
  if (!ex) throw new Error('Không tìm thấy bảng giá');
  db.prepare(`DELETE FROM price_book_items WHERE book_id=?`).run(ex.id);
  db.prepare(`DELETE FROM price_books WHERE id=?`).run(ex.id);
  audit('pricebook.delete', { id: ex.id, name: ex.name }, branch_id, user?.username || user?.name);
  return { ok: true };
}

/// Đặt giá riêng 1 SKU trong 1 bảng giá; price null/rỗng = xóa giá riêng
/// (quay về giá chung). Bảng 'default' thì cập nhật thẳng skus.price.
export function setPriceBookEntry(body = {}, branch_id = 'br1', user = {}) {
  const bookId = String(body.book_id || '').trim();
  const skuId = String(body.sku_id || '').trim();
  if (!bookId || !skuId) throw new Error('Thiếu book_id/sku_id');
  const sku = db.prepare(`SELECT id, name, vat, price_includes_vat FROM skus WHERE id=? AND branch_id=?`).get(skuId, branch_id);
  if (!sku) throw new Error('Không tìm thấy sản phẩm');
  const raw = body.price;
  const clear = raw === null || raw === undefined || raw === '';
  const price = clear ? null : Math.max(0, Math.round(Number(raw) || 0));

  if (bookId === 'default') {
    if (clear) throw new Error('Bảng giá chung phải có giá bán');
    const vat = sku.vat == null ? null : Number(sku.vat);
    const preTax = sku.price_includes_vat !== 0 && vat > 0 ? Math.round(price / (1 + vat / 100)) : price;
    db.prepare(`UPDATE skus SET price=?, price_pre_tax=?, price_updated_at=? WHERE id=?`)
      .run(price, preTax, now(), skuId);
    audit('pricebook.set_price', { sku_id: skuId, name: sku.name, price, book: 'default' }, branch_id, user?.username || user?.name);
    return { ok: true, price, price_pre_tax: preTax };
  }

  const book = db.prepare(`SELECT id FROM price_books WHERE id=? AND branch_id=?`).get(bookId, branch_id);
  if (!book) throw new Error('Không tìm thấy bảng giá');
  if (clear) {
    db.prepare(`DELETE FROM price_book_items WHERE book_id=? AND sku_id=?`).run(bookId, skuId);
  } else {
    db.prepare(`INSERT INTO price_book_items (book_id, sku_id, price, updated_at) VALUES (?,?,?,?)
      ON CONFLICT(book_id, sku_id) DO UPDATE SET price=excluded.price, updated_at=excluded.updated_at`)
      .run(bookId, skuId, price, now());
  }
  audit('pricebook.set_price',
    { sku_id: skuId, name: sku.name, price: clear ? '(về giá chung)' : price, book: bookId },
    branch_id, user?.username || user?.name);
  return { ok: true, price };
}

export function findSkuByBarcode(barcode, branch_id = 'br1', filters = {}) {
  const sec = retailSectionFor(branch_id, filters.channel);
  const forcedWh = !filters.warehouse_id && sec?.warehouse_id ? sec.warehouse_id : '';
  const mapChannel = filters.channel === 'fnb_retail' ? 'retail' : filters.channel;
  const channelWarehouseIds =
      forcedWh ? null : channelWarehouseFilter(branch_id, mapChannel);
  const wantWh = filters.warehouse_id || forcedWh;
  const rows = db.prepare(`SELECT * FROM skus WHERE branch_id=? AND barcode=? AND active=1 ORDER BY name`).all(branch_id, barcode);
  const row = rows
    .filter(s => !wantWh || (s.warehouse_id || fallbackWarehouse(branch_id, 'sku')) === wantWh)
    .find(s => !channelWarehouseIds || channelWarehouseIds.includes(s.warehouse_id || fallbackWarehouse(branch_id, 'sku')));
  return row
      ? withProductImage(applyChannelPrice(
          enrichStockRow('sku', row, wantWh), branch_id, filters.channel))
      : null;
}

export function createInventoryItem(body, branch_id = 'br1') {
  if (!body.name) throw new Error('Thiếu tên mặt hàng');
  const id = body.id || uid('i_');
  const warehouse_id = body.warehouse_id || fallbackWarehouse(branch_id, 'inventory');
  const item_type = ['ingredient', 'supply'].includes(body.item_type) ? body.item_type : 'ingredient';
  db.prepare(`INSERT INTO inventory_items
    (id,branch_id,name,unit,stock,min_stock,warehouse_id,item_type,barcode,category,cost,track_lot,expiry_required,active,note,units_json)
    VALUES (?,?,?,?,0,?,?,?,?,?,?,?,?,1,?,?)`).run(
    id, branch_id, body.name, body.unit || 'cái', parseFloat(body.min_stock) || 0,
    warehouse_id, item_type, body.barcode || null, body.category || null, parseFloat(body.cost) || 0,
    asBool(body.track_lot), asBool(body.expiry_required), body.note || null, JSON.stringify(normalizeUnits(body.units)));

  const opening = parseFloat(body.opening_stock || body.stock || 0);
  if (opening > 0) receiveStock(id, opening, branch_id, {
    warehouse_id,
    unit_cost: parseFloat(body.cost) || 0,
    lot_no: body.lot_no || 'OPENING',
    expiry_date: body.expiry_date || null,
    supplier: body.supplier || 'opening',
    movementType: 'opening',
  });
  audit('inventory.item.create', { id, name: body.name, item_type }, branch_id);
  emit('inventory:updated', { ids: [id] }, branch_id);
  return getItem('inventory', id, branch_id);
}

export function updateInventoryItem(id, body, branch_id = 'br1') {
  const cur = db.prepare(`SELECT * FROM inventory_items WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!cur) throw new Error('Mặt hàng kho bếp không tồn tại');
  const item_type = body.item_type !== undefined
    ? (['ingredient', 'supply'].includes(body.item_type) ? body.item_type : cur.item_type)
    : cur.item_type;
  db.prepare(`UPDATE inventory_items SET
      name=?, unit=?, min_stock=?, warehouse_id=?, item_type=?, barcode=?, category=?, cost=?,
      track_lot=?, expiry_required=?, active=?, note=?, units_json=?
    WHERE id=? AND branch_id=?`).run(
    textOr(body.name, cur.name),
    textOr(body.unit, cur.unit),
    numberOr(body.min_stock, cur.min_stock),
    textOr(body.warehouse_id, cur.warehouse_id || fallbackWarehouse(branch_id, 'inventory')),
    item_type,
    nullableText(body.barcode, cur.barcode),
    nullableText(body.category, cur.category),
    numberOr(body.cost, cur.cost || 0),
    boolOr(body.track_lot, cur.track_lot),
    boolOr(body.expiry_required, cur.expiry_required),
    boolOr(body.active, cur.active),
    nullableText(body.note, cur.note),
    body.units !== undefined ? JSON.stringify(normalizeUnits(body.units)) : (cur.units_json || '[]'),
    id,
    branch_id);
  audit('inventory.item.update', { id, name: body.name || cur.name }, branch_id);
  emit('inventory:updated', { ids: [id] }, branch_id);
  return getItem('inventory', id, branch_id);
}

export function deleteInventoryItem(id, branch_id = 'br1') {
  const cur = db.prepare(`SELECT * FROM inventory_items WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!cur) throw new Error('Mặt hàng kho bếp không tồn tại');
  cleanupStockMaster('inventory', id, branch_id);
  db.prepare(`DELETE FROM inventory_items WHERE id=? AND branch_id=?`).run(id, branch_id);
  audit('inventory.item.delete', { id, name: cur.name }, branch_id);
  emit('inventory:updated', { ids: [id], deleted: true }, branch_id);
  return { ok: true, deleted: id, name: cur.name };
}

export function createSku(body, branch_id = 'br1') {
  if (!body.name) throw new Error('Thiếu tên SKU');
  const id = body.id || uid('s_');
  const warehouse_id = body.warehouse_id || fallbackWarehouse(branch_id, 'sku');
  const price = parseInt(body.price) || 0;
  const priceIncludesVat = [false, 0, '0'].includes(body.price_includes_vat) ? 0 : 1;
  const vat = body.vat == null ? null : Math.min(100, Math.max(0, Number(body.vat) || 0));
  const pricePreTax = priceIncludesVat && vat > 0 ? Math.round(price / (1 + vat / 100)) : price;
  db.prepare(`INSERT INTO skus
    (id,branch_id,barcode,name,emoji,image,price,price_includes_vat,price_pre_tax,vat,cost,stock,min_stock,unit,warehouse_id,category,supplier,source_url,track_lot,expiry_required,active,units_json)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(
    id, branch_id, body.barcode || null, body.name, body.emoji || '📦', body.image || null,
    price, priceIncludesVat, pricePreTax, vat, parseInt(body.cost) || 0, 0, parseFloat(body.min_stock) || 0,
    body.unit || 'cái', warehouse_id, body.category || null, body.supplier || null, body.source_url || null,
    asBool(body.track_lot), asBool(body.expiry_required), 1, JSON.stringify(normalizeUnits(body.units)));

  const opening = parseFloat(body.opening_stock || body.stock || 0);
  if (opening > 0) receiveSku(id, opening, branch_id, {
    warehouse_id,
    unit_cost: parseFloat(body.cost) || 0,
    lot_no: body.lot_no || 'OPENING',
    expiry_date: body.expiry_date || null,
    supplier: body.supplier || 'opening',
    movementType: 'opening',
  });
  audit('sku.create', { id, name: body.name }, branch_id);
  emit('inventory:updated', { ids: [id] }, branch_id);
  return getItem('sku', id, branch_id);
}

export function deleteSku(id, branch_id = 'br1') {
  const cur = db.prepare(`SELECT * FROM skus WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!cur) throw new Error('SKU không tồn tại');
  cleanupStockMaster('sku', id, branch_id);
  db.prepare(`DELETE FROM skus WHERE id=? AND branch_id=?`).run(id, branch_id);
  audit('sku.delete', { id, name: cur.name }, branch_id);
  emit('inventory:updated', { ids: [id], deleted: true }, branch_id);
  return { ok: true, deleted: id, name: cur.name };
}

export function updateSku(id, body, branch_id = 'br1') {
  const cur = db.prepare(`SELECT * FROM skus WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!cur) throw new Error('SKU không tồn tại');
  const price = intOr(body.price, cur.price);
  const priceIncludesVat = boolOr(body.price_includes_vat, cur.price_includes_vat);
  const vat = body.vat !== undefined ? (body.vat == null ? null : Math.min(100, Math.max(0, Number(body.vat) || 0))) : cur.vat;
  const pricePreTax = priceIncludesVat && vat > 0 ? Math.round(price / (1 + vat / 100)) : price;
  db.prepare(`UPDATE skus SET
      barcode=?, name=?, emoji=?, image=?, price=?, price_includes_vat=?, price_pre_tax=?, vat=?, cost=?, min_stock=?, unit=?, warehouse_id=?,
      category=?, supplier=?, source_url=?, track_lot=?, expiry_required=?, active=?, units_json=?
    WHERE id=? AND branch_id=?`).run(
    nullableText(body.barcode, cur.barcode),
    textOr(body.name, cur.name),
    textOr(body.emoji, cur.emoji || '📦'),
    nullableText(body.image, cur.image),
    price,
    priceIncludesVat,
    pricePreTax,
    vat,
    intOr(body.cost, cur.cost || 0),
    numberOr(body.min_stock, cur.min_stock),
    textOr(body.unit, cur.unit || 'cái'),
    textOr(body.warehouse_id, cur.warehouse_id || fallbackWarehouse(branch_id, 'sku')),
    nullableText(body.category, cur.category),
    nullableText(body.supplier, cur.supplier),
    nullableText(body.source_url, cur.source_url),
    boolOr(body.track_lot, cur.track_lot),
    boolOr(body.expiry_required, cur.expiry_required),
    boolOr(body.active, cur.active),
    body.units !== undefined ? JSON.stringify(normalizeUnits(body.units)) : (cur.units_json || '[]'),
    id,
    branch_id);
  audit('sku.update', { id, name: body.name || cur.name }, branch_id);
  emit('inventory:updated', { ids: [id] }, branch_id);
  return getItem('sku', id, branch_id);
}

export function receiveStock(inventory_item_id, qty, branch_id = 'br1', options = {}) {
  receiveGeneric('inventory', inventory_item_id, qty, branch_id, options);
  checkAlerts(branch_id, [{ stockType: 'inventory', id: inventory_item_id }]);
  emit('inventory:updated', { ids: [inventory_item_id] }, branch_id);
  return getItem('inventory', inventory_item_id, branch_id);
}

export function receiveSku(sku_id, qty, branch_id = 'br1', options = {}) {
  receiveGeneric('sku', sku_id, qty, branch_id, options);
  checkAlerts(branch_id, [{ stockType: 'sku', id: sku_id }]);
  emit('inventory:updated', { ids: [sku_id] }, branch_id);
  return getItem('sku', sku_id, branch_id);
}

export function issueStock(stockType, item_id, qty, branch_id = 'br1', options = {}) {
  const consumed = issueGeneric(normalizeStockType(stockType), item_id, qty, branch_id, options);
  checkAlerts(branch_id, [{ stockType: normalizeStockType(stockType), id: item_id }]);
  emit('inventory:updated', { ids: [item_id] }, branch_id);
  return consumed;
}

export function adjustStock(inventory_item_id, newStock, branch_id = 'br1', options = {}) {
  return setStockLevel('inventory', inventory_item_id, newStock, branch_id, options);
}

export function adjustSku(sku_id, newStock, branch_id = 'br1', options = {}) {
  return setStockLevel('sku', sku_id, newStock, branch_id, options);
}

export function returnSku(sku_id, qty, ref, branch_id = 'br1', options = {}) {
  const lot = options.lot_id ? db.prepare(`SELECT * FROM stock_lots WHERE id=? AND branch_id=? AND item_type='sku' AND item_id=?`)
    .get(options.lot_id, branch_id, sku_id) : null;
  receiveGeneric('sku', sku_id, qty, branch_id, {
    ref,
    movementType: 'return',
    reason: 'retail_return',
    skipDocument: true,
    warehouse_id: lot?.warehouse_id || options.warehouse_id,
    lot_no: lot?.lot_no || options.lot_no,
    expiry_date: lot?.expiry_date || options.expiry_date,
    mfg_date: lot?.mfg_date || options.mfg_date,
    unit_cost: lot?.unit_cost || options.unit_cost,
    supplier: lot?.supplier || options.supplier,
  });
  emit('inventory:updated', { ids: [sku_id] }, branch_id);
}

// Chuyển hàng giữa 2 kho. Nhận MỘT mặt hàng (body.item_id/qty — tương thích cũ)
// hoặc NHIỀU dòng (body.lines=[{stock_type,item_id,qty,lot_id?,uom?}]) gom vào
// một phiếu chuyển duy nhất (giống phiếu Chuyển hàng KiotViet).
export function transferStock(body, branch_id = 'br1') {
  const from = body.from_warehouse_id;
  const to = body.to_warehouse_id;
  if (!from || !to || from === to) throw new Error('Phiếu chuyển kho thiếu thông tin');
  const whFrom = db.prepare(`SELECT id FROM warehouses WHERE id=? AND branch_id=?`).get(from, branch_id);
  const whTo = db.prepare(`SELECT id FROM warehouses WHERE id=? AND branch_id=?`).get(to, branch_id);
  if (!whFrom || !whTo) throw new Error('Kho nguồn hoặc kho đích không tồn tại');

  const rawLines = Array.isArray(body.lines) && body.lines.length ? body.lines : [body];
  // Kiểm tra TẤT CẢ các dòng trước khi đụng vào tồn: không để phiếu áp một nửa.
  const lines = rawLines.map((r) => {
    const stockType = normalizeStockType(r.stock_type || r.item_type);
    const item = getItem(stockType, r.item_id, branch_id);
    if (!item) throw new Error(`Mặt hàng không tồn tại: ${r.item_id || '?'}`);
    const qty = qtyNum(r.qty) * unitFactor(item, r.uom);
    // Guard: never move more than is really on hand at the source. Without this,
    // consumeLots would pad the shortfall with a phantom lot and the destination
    // would gain stock out of nothing (source goes negative). Transfer runs on lots.
    const availAtSource = r.lot_id
      ? currentStock(stockType, r.item_id, from, r.lot_id)
      : db.prepare(`SELECT COALESCE(SUM(qty_on_hand),0) s FROM stock_lots WHERE warehouse_id=? AND item_type=? AND item_id=? AND qty_on_hand>0`)
          .get(from, stockType, r.item_id).s;
    if (availAtSource + 0.000001 < qty) {
      throw new Error(`Không đủ tồn ở kho nguồn: ${item.name} (còn ${roundQty(availAtSource)} ${item.unit})`);
    }
    return { stockType, item, item_id: r.item_id, qty, lot_id: r.lot_id || null, lot_no: r.lot_no, expiry_date: r.expiry_date, supplier: r.supplier };
  });

  const doc = createDocument(branch_id, {
    type: 'transfer',
    warehouse_id: from,
    to_warehouse_id: to,
    reason: body.reason || 'transfer',
    ref: body.ref || null,
    note: body.note || null,
    created_by: body.created_by || null,
  });
  const touchedIds = [];
  for (const ln of lines) {
    const { stockType, item, item_id } = ln;
    const consumed = consumeLots(stockType, item_id, from, ln.qty, ln.lot_id);
    for (const c of consumed) {
      const lot = c.lot_id ? db.prepare(`SELECT * FROM stock_lots WHERE id=?`).get(c.lot_id) : null;
      const targetLot = upsertLot({
        branch_id,
        warehouse_id: to,
        item_type: stockType,
        item_id,
        lot_no: lot?.lot_no || ln.lot_no || 'TRANSFER',
        expiry_date: lot?.expiry_date || ln.expiry_date || null,
        mfg_date: lot?.mfg_date || null,
        unit_cost: lot?.unit_cost || item.cost || 0,
        supplier: lot?.supplier || ln.supplier || null,
        qty: c.qty,
      });
      recordMovement({ branch_id, stockType, item_id, warehouse_id: from, lot_id: c.lot_id, type: 'transfer_out', qty: -c.qty, ref: doc.code || doc.id, reason: body.reason, doc_id: doc.id, unit_cost: lot?.unit_cost || 0 });
      recordMovement({ branch_id, stockType, item_id, warehouse_id: to, lot_id: targetLot.id, type: 'transfer_in', qty: c.qty, ref: doc.code || doc.id, reason: body.reason, doc_id: doc.id, unit_cost: lot?.unit_cost || 0 });
      addDocumentLine(doc.id, stockType, item_id, c.lot_id, -c.qty, lot?.unit_cost || 0, lot?.expiry_date || null, 'transfer out');
      addDocumentLine(doc.id, stockType, item_id, targetLot.id, c.qty, lot?.unit_cost || 0, lot?.expiry_date || null, 'transfer in');
    }
    touchedIds.push(item_id);
  }
  audit('stock.transfer', { document: doc.code || doc.id, from, to, lines: lines.map(l => ({ item: l.item_id, qty: l.qty })) }, branch_id, body.created_by);
  emit('inventory:updated', { ids: touchedIds }, branch_id);
  return { ok: true, document_id: doc.id, code: doc.code };
}

// Xuất kho NHIỀU dòng gom một phiếu (dùng cho Xuất dùng nội bộ + Trả hàng nhập).
// Mỗi dòng đi qua issueGeneric với doc_id chung nên tồn/lô/movement chuẩn FEFO.
export function issueLinesDocumented({ type, warehouse_id, lines = [], reason = null, ref = null, note = null, created_by = null }, branch_id = 'br1') {
  if (!warehouse_id) throw new Error('Thiếu kho xuất');
  const wh = db.prepare(`SELECT id FROM warehouses WHERE id=? AND branch_id=?`).get(warehouse_id, branch_id);
  if (!wh) throw new Error('Kho xuất không tồn tại');
  // Validate hết trước khi trừ tồn để phiếu không bị áp một nửa.
  const checked = [];
  for (const r of Array.isArray(lines) ? lines : []) {
    const stockType = normalizeStockType(r.stock_type || r.item_type);
    const item = getItem(stockType, r.item_id, branch_id);
    if (!item) throw new Error(`Mặt hàng không tồn tại: ${r.item_id || '?'}`);
    const qty = qtyNum(r.qty) * unitFactor(item, r.uom);
    const available = currentStock(stockType, r.item_id, warehouse_id, r.lot_id || null);
    if (available + 0.000001 < qty) {
      throw new Error(`Không đủ tồn: ${item.name} (còn ${roundQty(available)} ${item.unit})`);
    }
    checked.push({ stockType, item_id: r.item_id, qty, lot_id: r.lot_id || null, note: r.note || null });
  }
  if (!checked.length) throw new Error('Chưa có dòng hàng để xuất');
  const doc = createDocument(branch_id, { type, warehouse_id, reason, ref, note, created_by });
  const touched = [];
  for (const ln of checked) {
    issueGeneric(ln.stockType, ln.item_id, ln.qty, branch_id, {
      warehouse_id,
      lot_id: ln.lot_id,
      movementType: type,
      ref: ref || doc.code || doc.id,
      reason: reason || type,
      doc_id: doc.id,
      note: ln.note,
    });
    touched.push({ stockType: ln.stockType, id: ln.item_id });
  }
  checkAlerts(branch_id, touched);
  emit('inventory:updated', { ids: touched.map(t => t.id) }, branch_id);
  return doc;
}

// Xuất dùng nội bộ (KiotViet "Xuất dùng nội bộ" — Mới): xuất hàng cho cửa hàng
// tự dùng (pha chế, dùng thử, hư hỏng…). Một phiếu XDNB nhiều dòng.
export function issueInternalUse(body = {}, branch_id = 'br1', user = {}) {
  const doc = issueLinesDocumented({
    type: 'internal_use',
    warehouse_id: body.warehouse_id,
    lines: body.lines,
    reason: String(body.reason || '').trim() || 'internal_use',
    ref: body.ref || null,
    note: String(body.note || '').trim() || null,
    created_by: user?.name || user?.username || null,
  }, branch_id);
  audit('inventory.internal_use', { document: doc.code || doc.id, lines: (body.lines || []).length }, branch_id, user?.username || user?.name);
  return getDocument(doc.id, branch_id);
}

export function applyStocktake({ warehouse_id, name, mode = 'partial', lines = [] }, branch_id = 'br1') {
  if (!warehouse_id) throw new Error('Thiếu kho kiểm');
  if (!Array.isArray(lines) || !lines.length) throw new Error('Chưa có dòng kiểm kho');
  const sid = uid('st_');
  db.prepare(`INSERT INTO stocktake_sessions (id,branch_id,warehouse_id,name,mode,status,created_at,approved_at)
    VALUES (?,?,?,?,?,'approved',?,?)`).run(sid, branch_id, warehouse_id, name || 'Kiểm kho', mode, now(), now());

  const insLine = db.prepare(`INSERT INTO stocktake_lines
    (id,session_id,item_type,item_id,lot_id,expected_qty,counted_qty,delta_qty,reason)
    VALUES (?,?,?,?,?,?,?,?,?)`);
  let changed = 0;
  for (const line of lines) {
    const stockType = normalizeStockType(line.stock_type || line.item_type);
    const item_id = line.item_id;
    const counted = parseFloat(line.counted_qty ?? line.stock);
    if (!item_id || !Number.isFinite(counted) || counted < 0) continue;
    const expected = currentStock(stockType, item_id, warehouse_id, line.lot_id);
    const delta = counted - expected;
    insLine.run(uid('stl_'), sid, stockType, item_id, line.lot_id || null, expected, counted, delta, line.reason || null);
    if (Math.abs(delta) < 0.000001) continue;
    if (delta > 0) {
      receiveGeneric(stockType, item_id, delta, branch_id, {
        warehouse_id,
        lot_no: line.lot_no || `COUNT-${sid.slice(-5)}`,
        expiry_date: line.expiry_date || null,
        movementType: 'stocktake',
        ref: sid,
        reason: line.reason || 'stocktake_gain',
      });
    } else {
      issueGeneric(stockType, item_id, Math.abs(delta), branch_id, {
        warehouse_id,
        lot_id: line.lot_id || null,
        movementType: 'stocktake',
        ref: sid,
        reason: line.reason || 'stocktake_loss',
      });
    }
    changed++;
  }
  audit('stocktake.approve', { session: sid, warehouse_id, changed }, branch_id);
  emit('inventory:updated', {}, branch_id);
  return { ok: true, session_id: sid, changed };
}

// ---- Kiểm kho theo phiếu (KiotViet StockTakes) -----------------------------
// Vòng đời: draft (Phiếu tạm) -> approved (Đã cân bằng kho) | cancelled (Đã hủy).
// applyStocktake cũ ở trên vẫn giữ cho luồng "điều chỉnh ngay" tương thích ngược.

// Chuẩn hoá + tính tồn dự kiến cho từng dòng kiểm. Dòng kiểm theo LÔ (file mẫu
// Lô 1/Lô 2…) so với tồn của đúng lô đó; dòng không lô so với tồn cả kho.
function normalizeStocktakeLines(rawLines, warehouse_id, branch_id) {
  const lines = [];
  for (const r of Array.isArray(rawLines) ? rawLines : []) {
    const stockType = normalizeStockType(r.stock_type || r.item_type);
    const item_id = String(r.item_id || '').trim();
    const counted = parseFloat(r.counted_qty ?? r.qty ?? r.stock);
    if (!item_id || !Number.isFinite(counted) || counted < 0) continue;
    const item = getItem(stockType, item_id, branch_id);
    if (!item) throw new Error(`Mặt hàng không tồn tại: ${item_id}`);
    const lot_no = String(r.lot_no || '').trim() || null;
    let lot_id = String(r.lot_id || '').trim() || null;
    if (!lot_id && lot_no) {
      lot_id = db.prepare(`SELECT id FROM stock_lots WHERE warehouse_id=? AND item_type=? AND item_id=? AND lot_no=?`)
        .get(warehouse_id, stockType, item_id, lot_no)?.id || null;
    }
    const expected = lot_no && !lot_id ? 0 : currentStock(stockType, item_id, warehouse_id, lot_id);
    lines.push({
      stock_type: stockType,
      item_id,
      lot_id,
      lot_no,
      expiry_date: String(r.expiry_date || '').trim() || null,
      counted_qty: counted,
      expected_qty: expected,
      delta_qty: counted - expected,
      note: String(r.note || r.reason || '').trim() || null,
    });
  }
  return lines;
}

function replaceStocktakeLines(session_id, lines) {
  db.prepare(`DELETE FROM stocktake_lines WHERE session_id=?`).run(session_id);
  const ins = db.prepare(`INSERT INTO stocktake_lines
    (id,session_id,item_type,item_id,lot_id,lot_no,expiry_date,expected_qty,counted_qty,delta_qty,reason,note)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`);
  for (const l of lines) {
    ins.run(uid('stl_'), session_id, l.stock_type, l.item_id, l.lot_id, l.lot_no, l.expiry_date,
      l.expected_qty, l.counted_qty, l.delta_qty, l.note, l.note);
  }
}

// Tạo mới hoặc sửa phiếu kiểm kho NHÁP. body.id => update (chỉ khi còn draft).
export function saveStocktakeSession(body = {}, branch_id = 'br1', user = {}) {
  const warehouse_id = String(body.warehouse_id || '').trim();
  if (!warehouse_id) throw new Error('Thiếu kho kiểm');
  const wh = db.prepare(`SELECT id FROM warehouses WHERE id=? AND branch_id=?`).get(warehouse_id, branch_id);
  if (!wh) throw new Error('Kho kiểm không tồn tại');
  const lines = normalizeStocktakeLines(body.lines, warehouse_id, branch_id);
  if (!lines.length) throw new Error('Chưa có dòng kiểm kho');
  const name = textOr(body.name, 'Kiểm kho');
  const note = String(body.note || '').trim() || null;
  const actorName = user?.name || user?.username || null;

  const existing = body.id
    ? db.prepare(`SELECT * FROM stocktake_sessions WHERE id=? AND branch_id=?`).get(body.id, branch_id)
    : null;
  if (body.id && !existing) throw new Error('Phiếu kiểm không tồn tại');
  if (existing) {
    if (existing.status !== 'draft') throw new Error('Chỉ sửa được phiếu kiểm ở trạng thái Phiếu tạm');
    db.prepare(`UPDATE stocktake_sessions SET warehouse_id=?, name=?, note=?, mode=? WHERE id=?`)
      .run(warehouse_id, name, note, body.mode === 'full' ? 'full' : 'partial', existing.id);
    replaceStocktakeLines(existing.id, lines);
    audit('stocktake.update', { session: existing.id, code: existing.code, lines: lines.length }, branch_id, actorName);
    emit('inventory:updated', { stocktake: existing.id }, branch_id);
    return getStocktakeSession(existing.id, branch_id);
  }

  const sid = uid('st_');
  const code = nextSeqCode('stocktake_sessions', branch_id, 'KK');
  db.prepare(`INSERT INTO stocktake_sessions (id,branch_id,code,warehouse_id,name,mode,status,note,created_by,created_at)
    VALUES (?,?,?,?,?,?,'draft',?,?,?)`)
    .run(sid, branch_id, code, warehouse_id, name, body.mode === 'full' ? 'full' : 'partial', note, actorName, now());
  replaceStocktakeLines(sid, lines);
  audit('stocktake.create', { session: sid, code, warehouse_id, lines: lines.length }, branch_id, actorName);
  emit('inventory:updated', { stocktake: sid }, branch_id);
  return getStocktakeSession(sid, branch_id);
}

// "Cân bằng kho": tính lại chênh lệch tại thời điểm duyệt rồi nhập/xuất bù để
// tồn kho khớp số đếm. Toàn bộ điều chỉnh gom vào MỘT phiếu kho type 'stocktake'.
export function approveStocktakeSession(id, branch_id = 'br1', user = {}) {
  const s = db.prepare(`SELECT * FROM stocktake_sessions WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!s) throw new Error('Phiếu kiểm không tồn tại');
  if (s.status !== 'draft') throw new Error('Phiếu kiểm đã cân bằng hoặc đã hủy');
  const rawLines = db.prepare(`SELECT * FROM stocktake_lines WHERE session_id=? ORDER BY rowid`).all(id);
  if (!rawLines.length) throw new Error('Phiếu kiểm chưa có dòng hàng');
  const actorName = user?.name || user?.username || null;
  const doc = createDocument(branch_id, {
    type: 'stocktake', warehouse_id: s.warehouse_id,
    ref: s.code || s.id, reason: 'stocktake_balance', note: s.note, created_by: actorName,
  });
  const updLine = db.prepare(`UPDATE stocktake_lines SET expected_qty=?, delta_qty=? WHERE id=?`);
  let changed = 0;
  const touched = [];
  for (const line of rawLines) {
    const stockType = normalizeStockType(line.item_type);
    // Lô có thể vừa được tạo/thay đổi sau khi lập phiếu — tính lại ngay lúc duyệt.
    let lot_id = line.lot_id;
    if (!lot_id && line.lot_no) {
      lot_id = db.prepare(`SELECT id FROM stock_lots WHERE warehouse_id=? AND item_type=? AND item_id=? AND lot_no=?`)
        .get(s.warehouse_id, stockType, line.item_id, line.lot_no)?.id || null;
    }
    const expected = line.lot_no && !lot_id ? 0 : currentStock(stockType, line.item_id, s.warehouse_id, lot_id);
    const delta = line.counted_qty - expected;
    updLine.run(expected, delta, line.id);
    if (Math.abs(delta) < 0.000001) continue;
    if (delta > 0) {
      receiveGeneric(stockType, line.item_id, delta, branch_id, {
        warehouse_id: s.warehouse_id,
        lot_no: line.lot_no || `COUNT-${(s.code || s.id).slice(-6)}`,
        expiry_date: line.expiry_date || null,
        movementType: 'stocktake',
        ref: s.code || s.id,
        reason: line.note || 'stocktake_gain',
        doc_id: doc.id,
      });
    } else {
      issueGeneric(stockType, line.item_id, Math.abs(delta), branch_id, {
        warehouse_id: s.warehouse_id,
        lot_id: lot_id || null,
        movementType: 'stocktake',
        ref: s.code || s.id,
        reason: line.note || 'stocktake_loss',
        doc_id: doc.id,
      });
    }
    touched.push({ stockType, id: line.item_id });
    changed++;
  }
  db.prepare(`UPDATE stocktake_sessions SET status='approved', approved_at=? WHERE id=?`).run(now(), id);
  checkAlerts(branch_id, touched);
  audit('stocktake.approve', { session: id, code: s.code, changed, document: doc.id }, branch_id, actorName);
  emit('inventory:updated', { stocktake: id }, branch_id);
  return getStocktakeSession(id, branch_id);
}

export function cancelStocktakeSession(id, branch_id = 'br1', user = {}) {
  const s = db.prepare(`SELECT * FROM stocktake_sessions WHERE id=? AND branch_id=?`).get(id, branch_id);
  if (!s) throw new Error('Phiếu kiểm không tồn tại');
  if (s.status !== 'draft') throw new Error('Chỉ hủy được phiếu kiểm ở trạng thái Phiếu tạm');
  db.prepare(`UPDATE stocktake_sessions SET status='cancelled', cancelled_at=? WHERE id=?`).run(now(), id);
  audit('stocktake.cancel', { session: id, code: s.code }, branch_id, user?.name || user?.username);
  emit('inventory:updated', { stocktake: id }, branch_id);
  return getStocktakeSession(id, branch_id);
}

export function getStocktakeSession(id, branch_id = 'br1') {
  const s = db.prepare(`
    SELECT s.*, w.name AS warehouse_name
    FROM stocktake_sessions s
    LEFT JOIN warehouses w ON w.id=s.warehouse_id
    WHERE s.id=? AND s.branch_id=?`).get(id, branch_id);
  if (!s) throw new Error('Phiếu kiểm không tồn tại');
  const lines = db.prepare(`
    SELECT l.*, COALESCE(i.name, sk.name) AS item_name, COALESCE(i.unit, sk.unit) AS unit,
      COALESCE(i.barcode, sk.barcode) AS barcode, sk.code AS item_code
    FROM stocktake_lines l
    LEFT JOIN inventory_items i ON i.id=l.item_id AND l.item_type='inventory'
    LEFT JOIN skus sk ON sk.id=l.item_id AND l.item_type='sku'
    WHERE l.session_id=?
    ORDER BY l.rowid`).all(id);
  return { ...s, lines, ...stocktakeTotals(lines) };
}

function stocktakeTotals(lines) {
  let total_counted = 0, total_delta = 0, delta_inc = 0, delta_dec = 0;
  for (const l of lines) {
    total_counted += l.counted_qty || 0;
    total_delta += l.delta_qty || 0;
    if ((l.delta_qty || 0) > 0) delta_inc += l.delta_qty;
    else delta_dec += l.delta_qty;
  }
  return { total_counted, total_delta, delta_inc, delta_dec };
}

export function listStocktakes(branch_id = 'br1', filters = {}) {
  if (typeof filters === 'number') filters = { limit: filters }; // chữ ký cũ (limit)
  const limit = Math.max(1, Math.min(500, parseInt(filters.limit) || 100));
  const params = [branch_id];
  let where = 's.branch_id=?';
  if (filters.status) {
    const statuses = String(filters.status).split(',').map(v => v.trim()).filter(Boolean);
    if (statuses.length) {
      where += ` AND s.status IN (${statuses.map(() => '?').join(',')})`;
      params.push(...statuses);
    }
  }
  if (filters.warehouse_id) { where += ' AND s.warehouse_id=?'; params.push(String(filters.warehouse_id)); }
  if (filters.from) { where += ' AND s.created_at>=?'; params.push(String(filters.from)); }
  if (filters.to) { where += ' AND s.created_at<=?'; params.push(String(filters.to)); }
  const search = searchTokens(filters.q);
  const rows = db.prepare(`
    SELECT s.*, w.name AS warehouse_name,
      (SELECT COUNT(*) FROM stocktake_lines l WHERE l.session_id=s.id) AS lines,
      (SELECT COALESCE(SUM(l.counted_qty),0) FROM stocktake_lines l WHERE l.session_id=s.id) AS total_counted,
      (SELECT COALESCE(SUM(l.delta_qty),0) FROM stocktake_lines l WHERE l.session_id=s.id) AS total_delta,
      (SELECT COALESCE(SUM(CASE WHEN l.delta_qty>0 THEN l.delta_qty ELSE 0 END),0) FROM stocktake_lines l WHERE l.session_id=s.id) AS delta_inc,
      (SELECT COALESCE(SUM(CASE WHEN l.delta_qty<0 THEN l.delta_qty ELSE 0 END),0) FROM stocktake_lines l WHERE l.session_id=s.id) AS delta_dec
    FROM stocktake_sessions s
    LEFT JOIN warehouses w ON w.id=s.warehouse_id
    WHERE ${where}
    ORDER BY s.created_at DESC LIMIT 5000`).all(...params);
  return rows.filter(row => matchesSearch([row.code, row.name, row.warehouse_name], search)).slice(0, limit);
}

export function listLots(branch_id = 'br1', filters = {}) {
  const rows = db.prepare(`
    SELECT l.*, w.name AS warehouse_name,
      COALESCE(i.name, s.name) AS item_name,
      COALESCE(i.unit, s.unit) AS unit,
      COALESCE(i.item_type, 'retail') AS item_kind
    FROM stock_lots l
    LEFT JOIN warehouses w ON w.id=l.warehouse_id
    LEFT JOIN inventory_items i ON i.id=l.item_id AND l.item_type='inventory'
    LEFT JOIN skus s ON s.id=l.item_id AND l.item_type='sku'
    WHERE l.branch_id=? AND l.qty_on_hand>0
    ORDER BY
      CASE WHEN l.expiry_date IS NULL THEN 1 ELSE 0 END,
      l.expiry_date ASC,
      l.received_at ASC`).all(branch_id);
  const maxDate = filters.expiring_days ? new Date(Date.now() + Number(filters.expiring_days) * 86400000).toISOString().slice(0, 10) : null;
  return rows
    .filter(l => !filters.warehouse_id || l.warehouse_id === filters.warehouse_id)
    .filter(l => !filters.item_type || l.item_type === filters.item_type)
    .filter(l => !maxDate || (l.expiry_date && l.expiry_date <= maxDate));
}

export function listMovements(branch_id = 'br1', filters = {}) {
  if (typeof filters === 'number') filters = { limit: filters }; // legacy signature
  const limit = Math.max(1, Math.min(500, parseInt(filters.limit) || 80));
  const params = [branch_id];
  let where = 'm.branch_id=?';
  // Movements are attributed to the warehouse actually deducted/received. Filtering
  // by warehouse keeps each warehouse's history correct even as warehouses are
  // added/removed — an empty warehouse shows no movements.
  if (filters.warehouse_id) { where += ' AND m.warehouse_id=?'; params.push(String(filters.warehouse_id)); }
  if (filters.item_type) { where += ' AND m.item_type=?'; params.push(String(filters.item_type)); }
  if (filters.item_id) { where += ' AND m.inventory_item_id=?'; params.push(String(filters.item_id)); }
  return db.prepare(`
    SELECT m.*,
      COALESCE(i.name, s.name) AS item_name,
      COALESCE(i.unit, s.unit) AS unit,
      COALESCE(i.item_type, 'retail') AS item_kind,
      w.name AS warehouse_name,
      l.lot_no,
      l.expiry_date
    FROM stock_movements m
    LEFT JOIN inventory_items i ON i.id=m.inventory_item_id AND (m.item_type='inventory' OR m.item_type IS NULL)
    LEFT JOIN skus s ON s.id=m.inventory_item_id AND m.item_type='sku'
    LEFT JOIN warehouses w ON w.id=m.warehouse_id
    LEFT JOIN stock_lots l ON l.id=m.lot_id
    WHERE ${where}
    ORDER BY m.created_at DESC LIMIT ?`).all(...params, limit);
}

// ---- Warehouse documents (electronic goods-receipt / goods-issue slips) ----
// ONLY real warehouse slips (receive/issue/transfer/stocktake). Sale/return docs
// are excluded IN SQL so the LIMIT applies to genuine slips, not sales.
export function listDocuments(branch_id = 'br1', filters = {}) {
  const limit = Math.max(1, Math.min(500, parseInt(filters.limit) || 60));
  const excludedTypes = [...SALE_DOC_TYPES];
  const params = [branch_id, ...excludedTypes];
  let where = `d.branch_id=? AND d.type NOT IN (${excludedTypes.map(() => '?').join(',')})`;
  if (filters.warehouse_id) {
    where += ' AND (d.warehouse_id=? OR d.to_warehouse_id=?)';
    params.push(String(filters.warehouse_id), String(filters.warehouse_id));
  }
  if (filters.type) { where += ' AND d.type=?'; params.push(String(filters.type)); }
  return db.prepare(`
    SELECT d.*, w.name AS warehouse_name, tw.name AS to_warehouse_name,
      (SELECT COUNT(*) FROM inventory_document_lines l WHERE l.document_id=d.id) AS line_count,
      (SELECT COALESCE(SUM(ABS(l.qty)*l.unit_cost),0) FROM inventory_document_lines l WHERE l.document_id=d.id) AS total_value
    FROM inventory_documents d
    LEFT JOIN warehouses w ON w.id=d.warehouse_id
    LEFT JOIN warehouses tw ON tw.id=d.to_warehouse_id
    WHERE ${where}
    ORDER BY d.created_at DESC LIMIT ?`).all(...params, limit);
}

export function getDocument(id, branch_id = 'br1') {
  const doc = db.prepare(`
    SELECT d.*, w.name AS warehouse_name, w.code AS warehouse_code, tw.name AS to_warehouse_name
    FROM inventory_documents d
    LEFT JOIN warehouses w ON w.id=d.warehouse_id
    LEFT JOIN warehouses tw ON tw.id=d.to_warehouse_id
    WHERE d.id=? AND d.branch_id=?`).get(id, branch_id);
  if (!doc) throw new Error('Phiếu không tồn tại');
  const branch = db.prepare(`SELECT name, address FROM branches WHERE id=?`).get(branch_id);
  const lines = db.prepare(`
    SELECT l.*, COALESCE(i.name, s.name) AS item_name, COALESCE(i.unit, s.unit) AS unit,
      lot.lot_no, lot.expiry_date
    FROM inventory_document_lines l
    LEFT JOIN inventory_items i ON i.id=l.item_id AND l.item_type='inventory'
    LEFT JOIN skus s ON s.id=l.item_id AND l.item_type='sku'
    LEFT JOIN stock_lots lot ON lot.id=l.lot_id
    WHERE l.document_id=?
    ORDER BY l.rowid`).all(id);
  return { ...doc, branch_name: branch?.name, branch_address: branch?.address, lines };
}

export function deductForOrder(order, branch_id = 'br1') {
  const getRecipe = db.prepare(`SELECT inventory_item_id, qty FROM recipes WHERE menu_item_id=?`);
  const touched = [];
  const shortages = [];
  const onShort = (s) => shortages.push(s);
  for (const it of order.items || []) {
    if (it.status === 'cancelled') continue;
    if (it.sku_id) {
      // Retail SKUs stay strict: you can't sell a physical unit you don't have.
      issueGeneric('sku', it.sku_id, it.qty, branch_id, { movementType: 'sale', ref: order.id, reason: 'retail_sale', lot_id: it.lot_id || null, skipDocument: true });
      touched.push({ stockType: 'sku', id: it.sku_id });
    } else if (it.menu_item_id) {
      for (const r of getRecipe.all(it.menu_item_id)) {
        const used = r.qty * it.qty;
        // Kitchen ingredients never block a sale: allow the count to go negative
        // and just warn, so an off recipe/inventory count can't stop the kitchen.
        issueGeneric('inventory', r.inventory_item_id, used, branch_id, { movementType: 'recipe', ref: order.id, reason: it.name, allowNegative: true, onShort, skipDocument: true });
        touched.push({ stockType: 'inventory', id: r.inventory_item_id });
      }
    }
  }
  if (shortages.length) {
    // Surface the shortfall (Nhật ký hoạt động + realtime) so staff restock/recount.
    audit('inventory.recipe.short', { order: order.id, shortages }, branch_id);
    emit('inventory:short', { order_id: order.id, shortages }, branch_id);
  }
  checkAlerts(branch_id, touched);
  emit('inventory:updated', { ids: touched.map(t => t.id) }, branch_id);
  return { shortages };
}

function receiveGeneric(stockType, item_id, qtyRaw, branch_id, options = {}) {
  const item = getItem(stockType, item_id, branch_id);
  if (!item) throw new Error('Mặt hàng không tồn tại');
  const qty = qtyNum(qtyRaw) * unitFactor(item, options.uom);
  const warehouse_id = options.warehouse_id || item.warehouse_id || fallbackWarehouse(branch_id, stockType);
  if (item.expiry_required && !options.expiry_date) throw new Error(`${item.name} bắt buộc nhập hạn sử dụng`);
  const doc = options.skipDocument
      ? null
      : (options.doc_id ? { id: options.doc_id } : createDocument(branch_id, {
          type: options.movementType || 'receipt',
          warehouse_id,
          supplier: options.supplier || item.supplier || null,
          ref: options.ref || null,
          reason: options.reason || null,
        }));
  const lot = upsertLot({
    branch_id,
    warehouse_id,
    item_type: stockType,
    item_id,
    lot_no: normalizeLotNo(item, options),
    mfg_date: options.mfg_date || null,
    expiry_date: options.expiry_date || null,
    received_at: options.received_at || now(),
    qty,
    unit_cost: parseFloat(options.unit_cost ?? item.cost ?? 0) || 0,
    supplier: options.supplier || item.supplier || null,
  });
  addSummaryStock(stockType, item_id, qty);
  recordMovement({
    branch_id, stockType, item_id, warehouse_id, lot_id: lot.id,
    type: options.movementType || 'receipt', qty, ref: options.ref || doc?.id || null,
    reason: options.reason || null, doc_id: doc?.id || null, unit_cost: lot.unit_cost || 0,
  });
  if (doc) addDocumentLine(doc.id, stockType, item_id, lot.id, qty, lot.unit_cost || 0, lot.expiry_date || null, options.note || null);
  audit(`${stockType}.receive`, { item: item_id, qty, lot: lot.lot_no }, branch_id);
  return lot;
}

function issueGeneric(stockType, item_id, qtyRaw, branch_id, options = {}) {
  const item = getItem(stockType, item_id, branch_id);
  if (!item) throw new Error('Mặt hàng không tồn tại');
  const qty = qtyNum(qtyRaw) * unitFactor(item, options.uom);
  const warehouse_id = options.warehouse_id || item.warehouse_id || fallbackWarehouse(branch_id, stockType);
  const available = currentStock(stockType, item_id, warehouse_id, options.lot_id || null);
  if (available + 0.000001 < qty) {
    // Strict by default (can't issue what you don't have). With allowNegative
    // (kitchen recipe deduction) we let it go negative and just surface a warning
    // so an off inventory count never blocks a sale.
    if (!options.allowNegative || options.lot_id) {
      throw new Error(`Không đủ tồn: ${item.name} (còn ${roundQty(available)} ${item.unit})`);
    }
    if (typeof options.onShort === 'function') {
      options.onShort({ stockType, item_id, name: item.name, unit: item.unit, available: roundQty(available), needed: roundQty(qty), short: roundQty(qty - available) });
    }
  }
  // Sale/order deductions record a movement only — NOT a warehouse slip. Slips
  // (Phiếu nhập/xuất) are for deliberate receive/issue/transfer/stocktake; the
  // sales record is the invoice/bill in the payments module, not a stock doc.
  const doc = options.skipDocument
      ? null
      : (options.doc_id ? { id: options.doc_id } : createDocument(branch_id, {
          type: options.movementType || 'issue',
          warehouse_id,
          ref: options.ref || null,
          reason: options.reason || null,
        }));
  const consumed = consumeLots(stockType, item_id, warehouse_id, qty, options.lot_id);
  addSummaryStock(stockType, item_id, -qty);
  for (const c of consumed) {
    recordMovement({
      branch_id, stockType, item_id, warehouse_id, lot_id: c.lot_id,
      type: options.movementType || 'issue', qty: -c.qty, ref: options.ref || doc?.id || null,
      reason: options.reason || null, doc_id: doc?.id || null, unit_cost: c.unit_cost || 0,
    });
    if (doc) addDocumentLine(doc.id, stockType, item_id, c.lot_id, -c.qty, c.unit_cost || 0, c.expiry_date || null, options.note || null);
  }
  audit(`${stockType}.issue`, { item: item_id, qty, type: options.movementType || 'issue' }, branch_id);
  return consumed;
}

function setStockLevel(stockType, item_id, newStockRaw, branch_id, options = {}) {
  const newStock = parseFloat(newStockRaw);
  if (!Number.isFinite(newStock) || newStock < 0) throw new Error('Tồn kiểm không hợp lệ');
  const item = getItem(stockType, item_id, branch_id);
  if (!item) throw new Error('Mặt hàng không tồn tại');
  const warehouse_id = options.warehouse_id || item.warehouse_id || fallbackWarehouse(branch_id, stockType);
  const cur = currentStock(stockType, item_id, warehouse_id);
  const delta = newStock - cur;
  if (Math.abs(delta) < 0.000001) return getItem(stockType, item_id, branch_id);
  if (delta > 0) receiveGeneric(stockType, item_id, delta, branch_id, { ...options, warehouse_id, movementType: 'stocktake', reason: options.reason || 'manual_count' });
  else issueGeneric(stockType, item_id, Math.abs(delta), branch_id, { ...options, warehouse_id, movementType: 'stocktake', reason: options.reason || 'manual_count' });
  checkAlerts(branch_id, [{ stockType, id: item_id }]);
  emit('inventory:updated', { ids: [item_id] }, branch_id);
  return getItem(stockType, item_id, branch_id);
}

function consumeLots(stockType, item_id, warehouse_id, qty, lot_id = null) {
  const rows = lot_id
    ? [selectedLot(stockType, item_id, warehouse_id, lot_id, qty)]
    : db.prepare(`
        SELECT * FROM stock_lots
        WHERE warehouse_id=? AND item_type=? AND item_id=? AND qty_on_hand>0
        ORDER BY CASE WHEN expiry_date IS NULL THEN 1 ELSE 0 END, expiry_date ASC, received_at ASC`).all(warehouse_id, stockType, item_id);
  let remaining = qty;
  const consumed = [];
  for (const lot of rows) {
    if (remaining <= 0) break;
    const take = Math.min(remaining, lot.qty_on_hand);
    db.prepare(`UPDATE stock_lots SET qty_on_hand=qty_on_hand-?, status=CASE WHEN qty_on_hand-?<=0 THEN 'depleted' ELSE status END WHERE id=?`)
      .run(take, take, lot.id);
    consumed.push({ lot_id: lot.id, qty: take, unit_cost: lot.unit_cost || 0, expiry_date: lot.expiry_date || null });
    remaining -= take;
  }
  if (remaining > 0.000001) {
    if (lot_id) throw new Error('Lot không đủ tồn');
    consumed.push({ lot_id: null, qty: remaining, unit_cost: 0, expiry_date: null });
  }
  return consumed;
}

function selectedLot(stockType, item_id, warehouse_id, lot_id, qty) {
  const lot = db.prepare(`SELECT * FROM stock_lots WHERE id=? AND warehouse_id=? AND item_type=? AND item_id=?`)
    .get(lot_id, warehouse_id, stockType, item_id);
  if (!lot) throw new Error('Lot không tồn tại');
  if (lot.qty_on_hand + 0.000001 < qty) throw new Error('Lot không đủ tồn');
  return lot;
}

function upsertLot({ branch_id, warehouse_id, item_type, item_id, lot_no, mfg_date = null, expiry_date = null, received_at = now(), qty, unit_cost = 0, supplier = null }) {
  const found = db.prepare(`SELECT * FROM stock_lots WHERE warehouse_id=? AND item_type=? AND item_id=? AND lot_no=?`)
    .get(warehouse_id, item_type, item_id, lot_no);
  if (found) {
    db.prepare(`UPDATE stock_lots SET qty_on_hand=qty_on_hand+?, unit_cost=?, supplier=COALESCE(?,supplier), expiry_date=COALESCE(?,expiry_date), mfg_date=COALESCE(?,mfg_date), status='active' WHERE id=?`)
      .run(qty, unit_cost, supplier, expiry_date, mfg_date, found.id);
    return db.prepare(`SELECT * FROM stock_lots WHERE id=?`).get(found.id);
  }
  const id = uid('lot_');
  db.prepare(`INSERT INTO stock_lots
    (id,branch_id,warehouse_id,item_type,item_id,lot_no,mfg_date,expiry_date,received_at,qty_on_hand,unit_cost,supplier,status,created_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'active', ?)`).run(
    id, branch_id, warehouse_id, item_type, item_id, lot_no, mfg_date, expiry_date, received_at, qty, unit_cost, supplier, now());
  return db.prepare(`SELECT * FROM stock_lots WHERE id=?`).get(id);
}

function normalizeLotNo(item, options = {}) {
  if (options.lot_no) return String(options.lot_no).trim();
  if (item.track_lot || item.expiry_required || options.expiry_date) {
    const d = new Date().toISOString().slice(0, 10).replaceAll('-', '');
    return `LOT-${d}-${uid('').slice(-5).toUpperCase()}`;
  }
  return 'NOLOT';
}

// Mã phiếu đọc được theo loại (giống KiotViet): PN000001, XK000001… Đánh số
// tăng dần theo chi nhánh + tiền tố; phiếu cũ không có mã vẫn hiển thị theo id.
const DOC_CODE_PREFIX = {
  receipt: 'PN', opening: 'PN', issue: 'XK', transfer: 'CH',
  stocktake: 'KK', internal_use: 'XDNB', purchase_return: 'THN',
};
function nextSeqCode(table, branch_id, prefix, width = 6) {
  const last = db.prepare(`SELECT code FROM ${table} WHERE branch_id=? AND code LIKE ? ORDER BY LENGTH(code) DESC, code DESC LIMIT 1`)
    .get(branch_id, prefix + '%');
  const seq = last ? (parseInt(String(last.code).slice(prefix.length)) || 0) + 1 : 1;
  return prefix + String(seq).padStart(width, '0');
}

function createDocument(branch_id, { type, warehouse_id = null, to_warehouse_id = null, supplier = null, ref = null, reason = null, note = null, created_by = null }) {
  const id = uid('doc_');
  const prefix = DOC_CODE_PREFIX[type];
  const code = prefix ? nextSeqCode('inventory_documents', branch_id, prefix) : null;
  db.prepare(`INSERT INTO inventory_documents (id,branch_id,code,warehouse_id,to_warehouse_id,type,status,supplier,ref,reason,note,created_by,created_at,posted_at)
    VALUES (?,?,?,?,?,?,'posted',?,?,?,?,?,?,?)`).run(id, branch_id, code, warehouse_id, to_warehouse_id, type, supplier, ref, reason, note, created_by, now(), now());
  return { id, code };
}

function addDocumentLine(document_id, item_type, item_id, lot_id, qty, unit_cost, expiry_date, note) {
  db.prepare(`INSERT INTO inventory_document_lines (id,document_id,item_type,item_id,lot_id,qty,unit_cost,expiry_date,note)
    VALUES (?,?,?,?,?,?,?,?,?)`).run(uid('dl_'), document_id, item_type, item_id, lot_id || null, qty, unit_cost || 0, expiry_date || null, note || null);
}

function recordMovement({ branch_id, stockType, item_id, warehouse_id, lot_id = null, type, qty, ref = null, reason = null, doc_id = null, unit_cost = 0 }) {
  db.prepare(`INSERT INTO stock_movements
    (id,branch_id,inventory_item_id,type,qty,ref,created_at,item_type,warehouse_id,lot_id,unit_cost,reason,doc_id)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(uid('sm_'), branch_id, item_id, type, qty, ref, now(), stockType, warehouse_id, lot_id, unit_cost, reason, doc_id);
}

function addSummaryStock(stockType, item_id, delta) {
  if (stockType === 'sku') db.prepare(`UPDATE skus SET stock=stock+? WHERE id=?`).run(delta, item_id);
  else db.prepare(`UPDATE inventory_items SET stock=stock+? WHERE id=?`).run(delta, item_id);
}

function currentStock(stockType, item_id, warehouse_id, lot_id = null) {
  if (lot_id) {
    return db.prepare(`SELECT COALESCE(qty_on_hand,0) stock FROM stock_lots WHERE id=? AND item_type=? AND item_id=? AND warehouse_id=?`)
      .get(lot_id, stockType, item_id, warehouse_id)?.stock || 0;
  }
  const lotRows = db.prepare(`SELECT COALESCE(SUM(qty_on_hand),0) stock FROM stock_lots WHERE item_type=? AND item_id=? AND warehouse_id=?`)
    .get(stockType, item_id, warehouse_id);
  if (lotRows && lotRows.stock > 0) return lotRows.stock;
  return getItem(stockType, item_id)?.stock || 0;
}

function enrichStockRow(stockType, row, warehouseFilter = null) {
  const warehouse_id = row.warehouse_id || fallbackWarehouse(row.branch_id || 'br1', stockType);
  const stock = warehouseFilter ? currentStock(stockType, row.id, warehouseFilter) : row.stock;
  return {
    ...row,
    stock,
    warehouse_id,
    stock_type: stockType,
    low: stock <= row.min_stock,
    track_lot: !!row.track_lot,
    expiry_required: !!row.expiry_required,
    active: !!row.active,
    units: parseUnits(row),
  };
}

function getItem(stockType, id, branch_id = null) {
  if (stockType === 'sku') {
    return branch_id
      ? db.prepare(`SELECT *, 'sku' AS stock_type FROM skus WHERE id=? AND branch_id=?`).get(id, branch_id)
      : db.prepare(`SELECT *, 'sku' AS stock_type FROM skus WHERE id=?`).get(id);
  }
  return branch_id
    ? db.prepare(`SELECT *, 'inventory' AS stock_type FROM inventory_items WHERE id=? AND branch_id=?`).get(id, branch_id)
    : db.prepare(`SELECT *, 'inventory' AS stock_type FROM inventory_items WHERE id=?`).get(id);
}

function cleanupStockMaster(stockType, id, branch_id) {
  if (stockType === 'inventory') db.prepare(`DELETE FROM recipes WHERE inventory_item_id=?`).run(id);
  db.prepare(`DELETE FROM stock_lots WHERE branch_id=? AND item_type=? AND item_id=?`).run(branch_id, stockType, id);
  db.prepare(`DELETE FROM stock_movements
    WHERE branch_id=? AND inventory_item_id=? AND (item_type=? OR (item_type IS NULL AND ?='inventory'))`)
    .run(branch_id, id, stockType, stockType);
  db.prepare(`DELETE FROM inventory_document_lines WHERE item_type=? AND item_id=?`).run(stockType, id);
  db.prepare(`DELETE FROM stocktake_lines WHERE item_type=? AND item_id=?`).run(stockType, id);
}

function normalizeStockType(v) {
  if (v === 'sku' || v === 'retail') return 'sku';
  return 'inventory';
}

function checkAlerts(branch_id, touched) {
  const seen = new Set();
  for (const t of touched) {
    const key = `${t.stockType}:${t.id}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const item = getItem(t.stockType, t.id);
    if (item && item.stock <= item.min_stock) {
      emit('inventory:alert', { id: t.id, name: item.name, stock: item.stock, min: item.min_stock, unit: item.unit }, branch_id);
    }
  }
}

function roundQty(n) {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

function normalizeWarehouseCode(v) {
  return String(v || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 32) || 'WAREHOUSE';
}
